<?php
$title = 'ACTIVITES PSYCHOSOCIALES ET NUTRITIONNELLES';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'actpsysocinutri')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->headScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('datatables/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('datatables/js/buttons.print.min.js'))
        ->prependFile($this->basePath('datatables/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('datatables/js/jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
        ->prependFile($this->basePath('themes/datas/js/chartist-pie.js'))
        ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/exporting.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right">
                    <div class="form-group">
                        <div class="col-sm-4">
                            <?php
                            echo $this->formInput($form->get('datedeb'));
                            echo $this->formElementErrors($form->get('datedeb'));
                            ?>
                        </div>
                        <div class="col-sm-4">
                            <?php
                            echo $this->formInput($form->get('datefin'));
                            echo $this->formElementErrors($form->get('datefin'));
                            ?>
                        </div>
                        <div class="col-sm-4">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        
       <div class="row">
                <div class="col-md-12">
                    <div class="suivpsy" data-highcharts-chart="8">
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabsuivpsy">
                    <thead>
                        <tr>
                            <th><font color="red">Activités</font></th>
                            <th><font color="red">Nombre de séances</font></th>
                            <th><font color="red">Nombre de bénéf</font</th>
                            <th><font color="red">Observations</font></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabsuivpsy as $tabsuivpsyc) :  ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($tabsuivpsyc['titre']); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivpsyc[1]); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivpsyc[2]); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivpsyc['obs']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <br/>
             <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="actcomm-datatable">
                    <thead>
                       <tr >
                            <th></th>
                            <th></th>
                            <th colspan="4">ACTIVITES COMMUNAUTAIRES</th>
                             <th></th>
                        </tr>
                        <tr>
                            <th></th>
                            <th></th>
                            <th colspan="4">Total des participations</th>
                            <th></th>
                            
                        </tr>
                        <tr>
                            <th>Activités</th>
                            <th>Nombre de session</th>
                            <th>Total des participants</th>
                            <th>Hommes</th>
                            <th>Femmes</th>
                            <th>Total</th>
                            <th>Observations</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php  foreach ($tabactcom as $k=> $tabactcomm) :?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabactcomm['nbsess']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactcomm['totpar']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactcomm['hom']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactcomm['fem']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactcomm['total']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactcomm['obs']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <br/>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabsuivpsy">
                    <thead>
                        <tr>
                            <th></th>
                            <th colspan="5">ACTIVITES INDIVIDUELLES</th>
                            <th></th>
                        </tr>
                        <tr>
                            <th></th>
                            <th></th>
                            <th colspan="4">Total des bénéficiaires</th>
                        </tr>
                        <tr>
                            <th>Activités</th>
                            <th>Total séances</th>
                            <th>Hommes</th>
                            <th>Femmes</th>
                            <th>Total</th>
                            <th>Observations</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabactind as $k => $tabactindi) :  ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabactindi['totalseanc']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactindi[1]); ?></td>
                                <td><?php echo $this->escapeHtml($tabactindi[2]); ?></td>
                                <td><?php echo $this->escapeHtml($tabactindi['total']); ?></td>
                                <td><?php echo $this->escapeHtml($tabactindi['obs']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <br/>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
        
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

<script>
    $(document).ready(function () {
  
$('#tabsuivpsy').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
$('#actcomm-datatable').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
    
    $(function () {
    $('.suivpsy').highcharts({
        chart: {
            type: 'bar'
        },credits: {
            enabled: false
        },
        data: {
                // table: 'highcharts_datatable'
                table: document.getElementById('tabsuivpsy')
            },
        title: {
            text: 'Nombre de participants par activité communautaire'
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            title: {
                text: null
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Nombres de participants',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        },
        tooltip: {
            valueSuffix: ' Sales'
        },
        exporting: {
                buttons: {
                    contextButton: {
                        menuItems: [
                            {
                                text: 'Exporter le graphe au format PNG',
                                    onclick: function () {
                                        this.exportChart({
                                            type: 'image/png'
                                        });
                                    }
                            }, 
                            {
                                text: 'Exporter le graphe au format JPEG',
                                    onclick: function () {
                                        this.exportChart({
                                            type: 'image/jpeg'
                                        });
                                    }
                            }, 
                            {
                                text: 'Exporter le graphe au format PDF',
                                    onclick: function () {
                                        this.exportChart({
                                            type: 'application/pdf'
                                        });
                                    }
                            }
                        ]
                               
                    }          
                }
                 
                
            },
        plotOptions: {
            bar: {
                dataLabels: {
                    enabled: true
                }
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -40,
            y: 80,
            floating: true,
            borderWidth: 1,
            backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
            shadow: true
        },
        credits: {
            enabled: false
        },
        series: [{
            name: 'Nb de bénéf',
            data: [107, 31, 635, 203, 2]
        }, {
            name: 'Nb de séances',
            data: [133, 156, 947, 408, 6]
        }]
    });
    });
    });
</script>