<?php
$title = 'Requêtes sur les dossiers';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'addrqtedoss',)));
$form->setAttribute('target', '_blank');
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->headScript()
        ->appendFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
echo $this->formHidden($form->get('requetedosshidden'));
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title"><?php echo $this->escapeHtml($title); ?></h4>
</div>
<div class="modal-body">
    <div class="row">

        <div class="col-sm-12"> 
            <div class="form-group">
                <label class="control-label col-sm-4">
                    <?php echo $this->formLabel($form->get('Listetitre')); ?>
                </label>
                <div class="col-sm-5">
                    <?php
                    echo $this->formSelect($form->get('Listetitre'));
                    echo $this->formElementErrors($form->get('Listetitre'));
                    ?>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-12"> 
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-requete">
                    <thead>
                        <tr>
                            <th>Requêtes sur</th>
                            <th>Visible</th>
                            <th>Condition</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="requetetable">

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-9   col-sm-offset-2">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title">Gestion des sous-requêtes</h3>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label class="control-label col-sm-3">
                            <?php echo $this->formLabel($form->get('Listerqtedoss')); ?>
                        </label>
                        <div class="col-sm-6">
                            <?php
                            echo $this->formSelect($form->get('Listerqtedoss'));
                            echo $this->formElementErrors($form->get('Listerqtedoss'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label col-sm-3">
                        </label>
                        <div class="col-sm-9 checkbox">
                            <label>
                                <input type="checkbox" name="Visible" class="primary" id="Visible" value="1" <?php if ($form->get('Visible')->getValue() == "1") echo 'checked="checked"'; ?>> Affichage
                                <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
                            </label>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label col-sm-3">
                        </label>
                        <div class="col-sm-9 checkbox">
                            <label>
                                <input type="checkbox" name="Statcond" class="primary"  id="Statcond" value="1" <?php if ($form->get('Statcond')->getValue() == "1") echo 'checked="checked"'; ?>> Critères de selection
                                <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
                            </label>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label col-sm-3">
                        </label>
                        <div class="col-sm-3">
                            <?php
                            echo $this->formSelect($form->get('Cond1'));
                            echo $this->formElementErrors($form->get('Cond1'));
                            ?>
                        </div>
                        <div class="col-sm-3">
                            <?php
                            echo $this->formInput($form->get('Cond2'));
                            echo $this->formElementErrors($form->get('Cond2'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group form-group-sm">
                        <label class="control-label col-sm-3">
                        </label>
                        <div class="col-sm-6">
                            <?php echo $this->formButton($form->get('ajtmodrkete')) ?> 
                      </div>
                        <div class="col-sm-3">
                            <span>
                                <button type="button" name="rest" value="Annuler" class="btn btn-default" aria-label="Close">Annuler</button>
                            </span>
                        </div>
                    </div>
                </div>

            </div>


        </div>
    </div>
</div>

<div class="modal-footer">
    <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
    <span>
        <button type="button" name="rest" value="Annuler" id="reset" class="btn btn-default" data-dismiss="modal" aria-label="Close">Annuler</button>
    </span>
</div>
<?php echo $this->form()->closeTag() ?>
</div>

<script>

    $(document).ready(function () {
        var modrqute = 0;
        var requetetable = null;
        var listerqtedoss = <?php echo json_encode($listerqtedoss); ?>;
        var tabcorresp = <?php echo json_encode($tabcorresp); ?>;
        var idrkete = 0;
        var analrequ = <?php echo json_encode($analrequ); ?>;
        analrequ = analrequ + "";
        analrequ = analrequ.split("xy9k");
        var Nume = null;
        var rowindex = null;
        var tr = null;
        var donnee;
        requetetable = $('#dataTables-requete').DataTable({
            "columnDefs": [
                {
                    "targets": [1],
                    /*"visible": false,
                     "searchable": false*/
                },
                {
                    "targets": [2],
                    /* "visible": false,
                     "searchable": false*/
                },
                {
                    "targets": [3],
                    /* "visible": false,
                     "searchable": false*/
                }
            ],
            "language": {
                "emptyTable": "aucune donnée disponible",
                "search": "Rechercher :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            },
            "bLengthChange": false,
            "info": false,
            "ordering": false,
            "searching": false,
            "iDisplayLength": 10,
            "aLengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]]
        });

        $('#ajtmodrkete').on('click', function () {
            var tab = Array();

            tab[0] = document.getElementById('Listerqtedoss').value;
            tab[1] = "0";
            if (document.getElementById("Visible").checked) {
                tab[1] = "1";
            }
            tab[2] = document.getElementById('Cond1').value;
            tab[3] = document.getElementById('Cond2').value;
            if (Nume) {
                var valeur = modification(tab);
                var donnee = Array();
                donnee[0] = listerqtedoss[tab[0]];
                var eyes;
                var cond;
                if (tab[1] === '1')
                {
                    eyes = '<span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color:green"></span>';
                }
                else
                {
                    eyes = '<span class="glyphicon glyphicon-eye-close" aria-hidden="true" style="color:red"></span>';
                }
                donnee[1] = eyes;
                cond = tab[2];
                if (cond === '0')
                {
                    cond = "";
                }
                var option = tabcorresp[tab[0]].split("$");
                if (cond)
                {
                    cond = parseInt(cond);
                    cond = option[cond - 1] + tab[3];
                }
                donnee[2] = cond;
                donnee[3] = '<a data-toggle="modal"  title="Modifier" class="mod btn btn-sm btn-success" href="#" id="' + Nume + '"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a> <a data-toggle="modal" title="Supprimer" class="btn btn-sm btn-danger" href="#" id="' + Nume + '"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>';


                requetetable.row(tr).data(donnee).draw();

                Nume = null;
            }
            else
            { //ajout
                ajout(tab);
                var eyes;
                var cond;
                if (tab[1] === '1')
                {
                    eyes = '<span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color:green"></span>';
                }
                else
                {
                    eyes = '<span class="glyphicon glyphicon-eye-close" aria-hidden="true" style="color:red"></span>';
                }
                cond = tab[2];
                if (cond === '0')
                {
                    cond = "";
                }
                var option = tabcorresp[tab[0]].split("$");
                if (cond)
                {
                    cond = parseInt(cond);
                    cond = option[cond - 1] + tab[3];
                }

                if (idrkete == 0)
                    idrkete = 1;
                else
                    idrkete += 4;
                requetetable.row.add([
                    listerqtedoss[tab[0]],
                    eyes,
                    cond + '',
                    '<a data-toggle="modal"  title="Modifier" class="mod btn btn-sm btn-success" href="#" id="' + idrkete + '"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a> <a data-toggle="modal" title="Supprimer" class="btn btn-sm btn-danger" href="#" id="' + idrkete + '"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>'
                ]).draw(false);
            }

            /*  $('#Dat_psy').val("");
             $('#Motipsy').val("");
             $('#Concpsy').val("");
             $('#Notapsy').val("");*/
        });

        $('#dataTables-requete tbody').on('click', '.mod.btn.btn-sm.btn-success', function () {

            tr = this.closest('tr');
            donnee = requetetable.row(tr).data();
            var id = parseInt(this.id);

            var valeur = affiche(id, $('#Listetitre').val());
            console.log(valeur);
            //document.getElementById("ajtmodrkete").value = "Modifier";
            $('#Listerqtedoss').val(valeur[id]);
            initcond();

            document.getElementById("Visible").checked = false;
            if (valeur[id + 1] === "1")
                document.getElementById("Visible").checked = true;
            document.getElementById("Statcond").checked = false;
            if (valeur[id + 2] !== "0")
                document.getElementById("Statcond").checked = true;
            $('#Cond1').val(valeur[id + 2]);
            $('#Cond2').val(valeur[id + 3]);
            Nume = parseInt(this.id);
        });
        $('#dataTables-requete tbody').on('click', '.btn.btn-sm.btn-danger', function () {
            var id = this.id;
            var tr = this.closest('tr');
            //donnee = requetetable.row(tr).remove();
            tr.remove();
        });
        $('#submit').on('click', function () {

            restore();
        });
        $('#Statcond').on('click', function () {

//alert($('#Statcond').val());
            if (document.getElementById("Statcond").checked)
            {
                document.getElementById('Cond1').disabled = false;
            }
            else
            {
                document.getElementById('Cond1').disabled = 'disabled';
                document.getElementById('Cond2').disabled = 'disabled';
            }

        });

        $('#Cond1').on('change', function () {
            // if($('#Cond1').val()==)zxc
            if ($('#Cond1 option:selected').text() === '>' || $('#Cond1 option:selected').text() === '<')
            {
                document.getElementById('Cond2').disabled = false;
            }
            else
            {
                document.getElementById('Cond2').disabled = 'disabled';
                document.getElementById('Cond2').value = '';
            }
        });

        $('#resetrkete').on('click', function () {
            Nume = null;
            document.getElementById("Listerqtedoss").value = "";
            document.getElementById("Cond1").value = "";
            document.getElementById("Cond2").value = "";
            document.getElementById("Visible").checked = false;
            document.getElementById("Statcond").checked = false;
        });

        $('#Listetitre').on('change', function () {
            requetetable.clear().draw();
            idrkete = 0;
            inittab();
        });
        $('#Listerqtedoss').on('change', function () {
            initcond();
        });

        function inittab()
        {
            var titre = $('#Listetitre').val();
            var strc = null;
            var chaine = "";
            for (var i = 0; i < (analrequ.length - 1); i++)
            {
                strc = analrequ[i].split("#");
                var j = 1;
                if (strc[0] === titre)  //si enreg a afficher
                {
                    while (j < strc.length - 1)
                    {
                        var exist = strc[j].indexOf(";");
                        if (exist !== -1) {
                            var eyes;
                            var cond;
                            if (strc[j + 1] === '1')
                            {
                                eyes = '<span class="glyphicon glyphicon-eye-open" aria-hidden="true" style="color:green"></span>';
                            }
                            else
                            {
                                eyes = '<span class="glyphicon glyphicon-eye-close" aria-hidden="true" style="color:red"></span>';
                            }
                            cond = strc[j + 2];
                            if (cond === '0')
                            {
                                cond = "";
                            }
                            var option = tabcorresp[strc[j]].split("$");
                            if (cond)
                            {
                                cond = parseInt(cond);
                                cond = option[cond - 1] + strc[j + 3];
                            }
                            idrkete = j;
                            requetetable.row.add([
                                listerqtedoss[strc[j]],
                                eyes,
                                cond + '',
                                '<a data-toggle="modal"  title="Modifier" class="mod btn btn-sm btn-success" href="#" id="' + idrkete + '"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a> <a data-toggle="modal" title="Supprimer" class="btn btn-sm btn-danger" href="#" id="' + idrkete + '""><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>'
                            ]).draw(false);
                        }
                        j++;

                    }
                    break;
                }
                else {
                    //chaine += strl[i] + "$";
                }
            }
            return(chaine);
        }
        function initcond()
        {
            $('#Cond1').empty();
            $('#Cond1').append($('<option>', {
                value: "",
                text: ""
            }));
            var option = tabcorresp[$('#Listerqtedoss').val()].split("$");
            for (var i = 0; i < option.length; i++) {
                $('#Cond1').append($('<option>', {
                    value: i + 1,
                    text: option[i]
                }));
            }
        }
        function ajout(tab)
        {
            var titre = $('#Listetitre').val();
            var strc = null;
            var chaine = "";
            for (var i = 0; i < (analrequ.length - 1); i++)
            {
                strc = analrequ[i].split("#");
                var j = 1;
                if (strc[0] === titre)  //si enreg a afficher
                {
                    analrequ[i] += tab[0] + "#" + tab[1] + "#" + tab[2] + "#" + tab[3] + "#";
                    console.log(analrequ[i]);
                    break;
                }
            }
            return(strc);
        }
        function modification(tab)
        {
            var titre = $('#Listetitre').val();
            var strc = null;
            var chaine = "";
            for (var i = 0; i < (analrequ.length - 1); i++)
            {
                strc = analrequ[i].split("#");
                var j = 1;
                if (strc[0] === titre)  //si enreg a afficher
                {
                    strc[Nume] = tab[0];
                    strc[Nume + 1] = tab[1];
                    strc[Nume + 2] = tab[2];
                    strc[Nume + 3] = tab[3];
                    var str = "";
                    for (var k = 0; k < strc.length - 1; k++)
                    {
                        str += strc[k] + "#";
                    }
                    analrequ[i] = str;
                    return(strc);
                }
            }
            return(strc);
        }
        function affiche(id, str)
        {

            var titre = $('#Listetitre').val();
            var strc = null;
            var chaine = "";
            for (var i = 0; i < (analrequ.length - 1); i++)
            {
                strc = analrequ[i].split("#");
                var j = 1;
                if (strc[0] === titre)  //si enreg a afficher
                {
                    // alert(strc[0]);
                    id = parseInt(id);
                    break;
                }
            }
            return(strc);
        }
        function restore()
        {
            var strc = "";
            for (var i = 0; i < (analrequ.length - 1); i++)
            {
                strc += analrequ[i] + "xy9k";

            }
            $('#requetedosshidden').val(strc);
            // alert(strc);
            return(strc);
        }

    });



</script>