<?php
$title = 'Activité de dépistage';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'depistage')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/exporting.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right" style="margin-right: 15px;">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datedeb'));
                            echo $this->formElementErrors($form->get('datedeb'));
                            ?>
                        </div>
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datefin'));
                            echo $this->formElementErrors($form->get('datefin'));
                            ?>
                        </div>
                        <div class="col-sm-2">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="serologie" data-highcharts-chart="1">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="profil" data-highcharts-chart="2">
                        </div>
                    </div>

                    <br/>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="depistable">
                                <thead>
                                    <tr>
                                        <th>Dépistage</th>
                                        <th>Homme</th>
                                        <th>Femme</th>
                                        <th>Total</th>
                                        <th>Poucentage</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($tabdepis as $tabdepi) : ?>
                                        <tr>
                                            <td><?php echo $this->escapeHtml($tabdepi['titre']); ?></td>
                                            <td><?php echo $this->escapeHtml($tabdepi[1]); ?></td>
                                            <td><?php echo $this->escapeHtml($tabdepi[2]); ?></td>
                                            
                                            <td><?php 
                                            
                                            if ($tabdepi['titre'] == 'Total')
                                                echo '<a title="Voir detail"  data-toggle="modal" title="Détails" href="#detailsdepistage">'
                                                    ."<span class='label label-primary'>". $this->escapeHtml($tabdepi[3])."</span></a>";
                                            else    
                                            echo $this->escapeHtml($tabdepi[3]); 
                                            
                                            ?></td>
                                            
                                            
                                            <td><?php echo $this->escapeHtml($tabdepi[4]); ?></td>

                                        </tr> 
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="depisprofil">
                                <thead>
                                    <tr>
                                        <th>Profil</th>
                                        <th>Hommes</th>
                                        <th>Femmes</th>
                                        <th>Total</th>
                                        <th>Poucentage</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($tabdepisprofil as $tabdepisprof) : ?>
                                        <tr>
                                            <td><?php echo $this->escapeHtml($tabdepisprof['titre']); ?></td>
                                            <td><?php echo $this->escapeHtml($tabdepisprof[1]); ?></td>
                                            <td><?php echo $this->escapeHtml($tabdepisprof[2]); ?></td>
                                            <td><?php echo $this->escapeHtml($tabdepisprof[3]); ?></td>
                                            <td><?php echo $this->escapeHtml($tabdepisprof[4]); ?></td>

                                        </tr> 
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">

            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<div class="modal fade" id="detailsdepistage" tabindex="-1" role="dialog" aria-labelledby="details" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Dépistage - Détails</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="examples col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche1">
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<script>

    $('#depistable').DataTable({
        dom: 'Bfrtip',
        "buttons": [
            {
                extend: 'collection',
                text: 'Exporter la liste',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copier',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa fa-print"></i> Imprimer',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'excel',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        className: 'btn btn-primary',
                    }
                ],
                className: 'btn btn-primary',
            }
        ],
        "ordering": false,
        "searching": false,
        "paging":   false,
        "info":     false,
        language: {
            buttons: {
                copyTitle: 'Ajouté au presse-papiers',
                /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                copySuccess: {
                    _: '%d lignes copiées',
                    1: '1 ligne copiée'
                }
            },
            "emptyTable": "aucune donnée disponible",
            "search": "Chercher:",
            "zeroRecords": "Aucun enregistrements correspondants trouvés",
            "paginate": {
                "first": "Premier",
                "last": "Dernier",
                "next": "Suivant",
                "previous": "Précédent"
            },
        }
    });
    $('#depisprofil').DataTable({
        dom: 'Bfrtip',
        "buttons": [
            {
                extend: 'collection',
                text: 'Exporter la liste',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copier',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa fa-print"></i> Imprimer',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'excel',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        className: 'btn btn-primary',
                    }
                ],
                className: 'btn btn-primary',
            }
        ],
        "ordering": false,
        "searching": false,
        "paging":   false,
        "info":     false,
        language: {
            buttons: {
                copyTitle: 'Ajouté au presse-papiers',
                /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                copySuccess: {
                    _: '%d lignes copiées',
                    1: '1 ligne copiée'
                }
            },
            "emptyTable": "aucune donnée disponible",
            "search": "Chercher:",
            "zeroRecords": "Aucun enregistrements correspondants trouvés",
            "paginate": {
                "first": "Premier",
                "last": "Dernier",
                "next": "Suivant",
                "previous": "Précédent"
            },
        }
    });
</script>
<script>
    var tabdepis = <?php echo json_encode($tabdepis); ?>;
    var tabdepisprofil = <?php echo json_encode($tabdepisprofil); ?>;
    function extract(tabdepis, chaine, pourcent) {
        var str = chaine.split("#");
        var result = Array();
        for (var indice in tabdepis)
        {
            var test = str.indexOf(tabdepis[indice]['titre']);
            if (test != "-1")
                result[tabdepis[indice]['titre']] = tabdepis[indice][pourcent];

        }
        return result;
    }
    $(function () {
        var chaine = "Positifs#Négatifs#Indéterminés";
        var pourcent = 4;
        var result = extract(tabdepis, chaine, pourcent);
        $('.serologie').highcharts({
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Répartition des résultats de dépistage'
            },
            exporting: {
                buttons: {
                    contextButton: {
                        menuItems: [
                            {
                                text: 'Exporter le graphe au format PNG',
                                onclick: function () {
                                    this.exportChart({
                                        type: 'image/png'
                                    });
                                }
                            },
                            {
                                text: 'Exporter le graphe au format JPEG',
                                onclick: function () {
                                    this.exportChart({
                                        type: 'image/jpeg'
                                    });
                                }
                            },
                            {
                                text: 'Exporter le graphe au format PDF',
                                onclick: function () {
                                    this.exportChart({
                                        type: 'application/pdf'
                                    });
                                }
                            }
                        ]

                    }
                }


            },
            credits: {
                enabled: false
            },
            subtitle: {
                //text: 'Click the slices to view versions. Source: netmarketshare.com.'
            },
            plotOptions: {
                series: {
                    dataLabels: {
                        enabled: true,
                        format: '<span style="font-size:12px" >{point.name}: {point.y:.0f}% </span>'
                    }
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.0f}%</b><br/>'
            },
            series: [{
                    name: 'Sérologie',
                    colorByPoint: true,
                    data: [{
                            name: 'Positifs',
                            y: parseInt(result['Positifs'])
                        }, {
                            name: 'Négatifs',
                            y: parseInt(result['Négatifs'])
                        }, {
                            name: 'Indéterminés',
                            y: parseInt(result['Indéterminés'])
                        }
                    ]
                }]
        });
        var chaine = "VIH 1#VIH 2#VIH 1+2";
        var pourcent = 4;
        var result = extract(tabdepisprofil, chaine, pourcent);
        $('.profil').highcharts({
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Répartition des résultats de dépistage par type de VIH'
            },
            credits: {
                enabled: false
            },
            plotOptions: {
                series: {
                    dataLabels: {
                        enabled: true,
                        format: '<span style="font-size:12px" >{point.name}: {point.y:.0f}% </span>'
                    }
                }
            },
            exporting: {
                buttons: {
                    contextButton: {
                        menuItems: [
                            {
                                text: 'Exporter le graphe au format PNG',
                                onclick: function () {
                                    this.exportChart({
                                        type: 'image/png'
                                    });
                                }
                            },
                            {
                                text: 'Exporter le graphe au format JPEG',
                                onclick: function () {
                                    this.exportChart({
                                        type: 'image/jpeg'
                                    });
                                }
                            },
                            {
                                text: 'Exporter le graphe au format PDF',
                                onclick: function () {
                                    this.exportChart({
                                        type: 'application/pdf'
                                    });
                                }
                            }
                        ]

                    }
                }


            },
            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.0f}%</b><br/>'
            },
            series: [{
                    name: 'Sérologie',
                    colorByPoint: true,
                    data: [{
                            name: 'VIH 1',
                            y: parseInt(result['VIH 1']),
                        }, {
                            name: 'VIH 2',
                            y: parseInt(result['VIH 2']),
                        }, {
                            name: 'VIH 1+2',
                            y: parseInt(result['VIH 1+2']),
                        }
                    ]
                }],
        });
    });
     var data1 = <?php echo $detailsdepistage; ?>;
    $('#tabaffiche1').DataTable({
        dom: 'Bfrtip',
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },
            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tDépistage\n\n" + csv;
                }
            },
            {
                extend: 'excel',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tDépistage\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        data: data1,
        columns: [
            {data: 'Ref', title: '<b>N° de depistage </b>'},
            {data: 'Age_', title: '<b>Age </b>'},
            {data: 'Sexe', title: '<b>Sexe </b>'},
            {data: 'ConfSero', title: '<b> Serologie </b>'},
            {data: 'ConfSeroTyp_', title: '<b> Type de Serologie </b>'},
            {data: 'ConfDat_', title: '<b> Date de confirmation</b>'},
        ],
    });
</script>