<?php
$title = 'Extraction BDD Amnir Echiva';

$this->headTitle($title);
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
 $this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
         ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
          ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
           ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
          ->prependFile($this->basePath('jszip.min.js'))
       ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
         ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'));
        
?>
<div class="panel panel-primary-border-top">
    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
            <?php echo $this->escapeHtml($title); ?>
        </h4>
        <div class="clearfix"></div>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <br/>
        <div class="table-responsive">
            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche">
            </table>
        </div>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
    </div>
</div>
<script>
    $('#medicons-datatable').DataTable({
        dom: 'Bfrtip',
        "buttons": [
            {
                extend: 'collection',
                text: 'Exporter la liste',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copier',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa fa-print"></i> Imprimer',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'excel',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        className: 'btn btn-primary',
                    }
                ],
                className: 'btn btn-primary',
            }
        ],
        "ordering": false,
        language: {
            buttons: {
                copyTitle: 'Ajouté au presse-papiers',
                /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                copySuccess: {
                    _: '%d lignes copiées',
                    1: '1 ligne copiée'
                }
            },
            "emptyTable": "aucune donnée disponible",
            "search": "Chercher:",
            "zeroRecords": "Aucun enregistrements correspondants trouvés",
            "paginate": {
                "first": "Premier",
                "last": "Dernier",
                "next": "Suivant",
                "previous": "Précédent"
            },
        }
    });
    var data = <?php echo $details; ?>;
    $('#tabaffiche').DataTable({
        data: data,
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },

/*

            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },*/
	    {
	        extend: 'csvHtml5',
		text: '<span class="glyphicon glyphicon-export"></span> CSV ',
		className: 'btn btn-success btn-outline btn-rounded',
		exportOptions: {
			columns: ':visible',
			format: {
				body: function(data, row, column, node) {
					data = $('<p>' + data + '</p>').text();
					data = ($.isNumeric(data)) ? data.toString().replace('.', ',') : data;
					return data;
				}
			}
		},
		 customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }

},



            {
                extend: 'excel',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        columns: [
            {data: 'Ref_', title: '<b>N° Dossier </b>'},
            {data: 'RensNom_', title: '<b>Nom </b>'},
            {data: 'RensPnom', title: '<b>Prenom </b>'},
            {data: 'RensAge_', title: '<b>Age </b>'},
            {data: 'RensSexe', title: '<b>Sexe </b>'},
            {data: 'RensDeceDat_', title: "<b>Date de décès </b>"},
            {data: 'RensChrg', title: "<b>Prise en charge </b>"},
            {data: 'OuvrDat_', title: "<b>Date d'inscription </b>"},
            // {data: 'Nbrcons', title: "<b>Nombre de consultation </b>"},
            {data: 'derncons', title: "<b>Date Dernière Consultation  </b>"},
            {data: 'Arv_Desi', title: "<b>Protocole ARV en cours </b>"},
            {data: 'arvfirstdeliv', title: "<b>Date première délivrance ARV </b>"},
            {data: 'arvlastdeliv', title: "<b>Date dernière délivrance ARV </b>"},
            {data: 'firstdeliv', title: "<b>Date première délivrance </b>"},
            {data: 'lastdeliv', title: "<b>Date dernière délivrance </b>"},
            {data: 'MediSeroTyp_', title: "<b>Type de sérologie </b>"},
            { data: 'commfirstpart',title:"<b>Date première participation Activité communautaire</b>" },
            { data: 'commlastpart',title:"<b>Date dernière participation Activité communautaire</b>" },
            {data: 'RensTel_', title: "<b>Telephone </b>"},
            {data: 'Dat_initImc_info', title: "<b>Date Imc Initial</b>"},
            {data: 'initImc_info', title: "<b>Imc initial</b>"},
            {data: 'Dat_dernImc_info', title: "<b>Date Dernier Imc </b>"},
            {data: 'dernImc_info', title: "<b>Dernier Imc </b>"},
            {data: 'Dat_initConc_info', title: "<b>Date Stade OMS Initial</b>"},
            {data: 'initConc_info', title: "<b>Stade OMS initial</b>"},
            {data: 'Dat_dernConc_info', title: "<b>Date Dernier Stade OMS </b>"},
            {data: 'dernConc_info', title: "<b>Dernier Stade OMS </b>"},
            {data: 'derngrosaccouch', title: "<b>Date d'accouchement dernière grossesse</b>"},
            {data: 'derngrosaccouchprev', title: "<b>Date prévue d'accouchement dernière grossesse</b>"},
            {data: 'derngrossaisi', title: "<b>Date de saisie dernière grossesse</b>"},
            {data: 'Dat_initCd40', title: "<b>Date Cd4 Initial</b>"},
            {data: 'initCd40', title: "<b>Cd4 initial</b>"},
            {data: 'Dat_dernCd40', title: "<b>Date Dernier Cd4</b>"},
            {data: 'dernCd40', title: "<b>Dernier Cd4</b>"},
            {data: 'Dat_initPcr0', title: "<b>Date  Charge Virale (UI/ml) Initial</b>"},
            {data: 'initPcr0', title: "<b> Charge Virale (UI/ml) initial</b>"},
            {data: 'Dat_dernPcr0', title: "<b>Date Dernier  Charge Virale (UI/ml)</b>"},
            {data: 'dernPcr0', title: "<b>Dernier  Charge Virale (UI/ml)</b>"},
            {data: 'dernrdv', title: "<b>Date Dernière rendez-vouz  </b>"},
            {data: 'dernvisite', title: "<b>Date Dernière visite  </b>"},
        ],
    });
    /* $('#detailbtn').on('click', function () { alert('sdf');
     document.getElementById('testinnn').innerHTML = document.getElementById('tabaffiche').innerHTML;
     //  document.getElementById('tabaffiche').innerHTML;
     });*/
</script>
