<?php
$title = 'HOSPITALISATIONS DE JOUR';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'hospdj')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
        ->prependFile($this->basePath('themes/datas/js/chartist-pie.js'))
        ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right" style="margin-right: 15px;">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datedeb'));
                            echo $this->formElementErrors($form->get('datedeb'));
                            ?>
                        </div>
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datefin'));
                            echo $this->formElementErrors($form->get('datefin'));
                            ?>
                        </div>
                        <div class="col-sm-2">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
       <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" >
                    <thead>
                        <tr>
                            <th>Nombre d'hospitalisation de jour</th>
                            <th>Nombre</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabnbhosp as $k=>$tabnbhos) :?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabnbhos['valeur']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <br/>
            <div class="row">
                <div class="col-md-12">
                    <div class="hospmoti" data-highcharts-chart="6">
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" >
                    <thead>
                        <tr>
                            <th>Motifs des hospitalisations de jour</th>
                            <th>Nombre</th>
                            <th>Pourcentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabmotihosp as $k=> $tabmotihos) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabmotihos['valeur']); ?></td>
                                <td><?php echo $this->escapeHtml($tabmotihos['pourcentage']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" >
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Nombre</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabrefhospnat as $tabrefhospn) :?>
                            <tr>
                                <td><?php echo $this->escapeHtml($tabrefhospn['titrep']); ?></td>
                                <td><?php echo $this->escapeHtml($tabrefhospn['titre']); ?></td>
                                <td><?php echo $this->escapeHtml($tabrefhospn['valeur']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
        
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

<script>
    $(document).ready(function () {
    var tabmotihosp = <?php echo json_encode($tabmotihosp); ?>;
    function extract(tabdepis, chaine, pourcent) {
        var str = chaine.split("#");
        var result = Array();
            
        for (var indice in tabdepis)
        {
                result[indice] = tabdepis[indice]['pourcentage'];
        }
        return result;
    }
    $(function () {
    var chaine = "Diarrhées et vomissements#Altération de l’état général#Candidose buccale#Anémie#Paludisme#Fièvre intermittente#Pneumopathies#Autres";
        var pourcent = 2;
        var result = extract(tabmotihosp, chaine, pourcent);
        
        $('.hospmoti').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Répartition des hospitalisations de jour par motif'
            },
              credits: {
                enabled:false
            },
            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.0f}%</b><br/>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{
                name: 'Motifs',
                colorByPoint: true,
                data: [{
                    name: 'Diarrhées et vomissements',
                    y: parseInt(result['Diarrhées et vomissements']),
                    sliced: true
                }, {
                    name: 'Altération de l’état général',
                    y: parseInt(result['Altération de l’état général']),
                    sliced: true
                }, {
                    name: 'Candidose buccale',
                    y: parseInt(result['Candidose buccale']),
                    sliced: true
                }, {
                    name: 'Anémie',
                    y: parseInt(result['Anémie']),
                    sliced: true
                }, {
                    name: 'Paludisme',
                    y: parseInt(result['Paludisme']),
                    sliced: true
                },{
                    name: 'Fièvre intermittente',
                    y: parseInt(result['Fièvre intermittente']),
                    sliced: true
                },{
                    name: 'Pneumopathies',
                    y: parseInt(result['Pneumopathies']),
                    sliced: true
                },{
                    name: 'Autres',
                    y: parseInt(result['Autres']),
                    sliced: true
                }]
            }]
        });
    });
    });
</script>