<?php
$title = 'Consultations médicales';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'medicons')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'));
// ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
// ->prependFile($this->basePath('themes/datas/js/chartist-pie.js'))
// ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
// ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/data.js'))
// ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="panel panel-primary-border-top">
    <div class="panel-heading clearfix">
        <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
            <?php echo $this->escapeHtml($title); ?>
        </h4>
        <div class="btn-group pull-right" style="margin-right: 15px;">
            <div class="form-group">
                <div class="col-sm-5">
                    <?php
                    echo $this->formInput($form->get('datedeb'));
                    echo $this->formElementErrors($form->get('datedeb'));
                    ?>
                </div>
                <div class="col-sm-5">
                    <?php
                    echo $this->formInput($form->get('datefin'));
                    echo $this->formElementErrors($form->get('datefin'));
                    ?>
                </div>
                <div class="col-sm-2">
                    <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <br/>
        <div class="table-responsive">
            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="medicons-datatable">
                <thead>
                    <tr>
                        <th>Consultations médicales</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($tabmedicons as $tabmed) : ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($tabmed['titre']); ?></td>
                            <td>
                                <?php
                                if ($tabmed['titre'] !== 'Nombre de patients ayant consulté plusieurs fois')
                                    echo $this->escapeHtml($tabmed[1]);
                                else
                                    echo '<a title="Voir detail" data-toggle="modal" title="Détails" href="#details">'
                                    . $this->escapeHtml($tabmed[1])
                                    . '</a>';
                                ?>
                            </td>
                        </tr> 
                    <?php endforeach; ?>
                </tbody>
            </table>
         
        
        </div>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
    </div>
</div>

<?php echo $this->form()->closeTag() ?>


<div class="modal fade" id="details" tabindex="-1" role="dialog" aria-labelledby="details" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Consultation médicales - Détails</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="examples col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche">
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>



<script>
    $('#medicons-datatable').DataTable({
        dom: 'Bfrtip',
        "buttons": [
            {
                extend: 'collection',
                text: 'Exporter la liste',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copier',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa fa-print"></i> Imprimer',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'excel',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        className: 'btn btn-primary',
                    }
                ],
                className: 'btn btn-primary',
            }
        ],
        "ordering": false,
        language: {
            buttons: {
                copyTitle: 'Ajouté au presse-papiers',
                /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                copySuccess: {
                    _: '%d lignes copiées',
                    1: '1 ligne copiée'
                }
            },
            "emptyTable": "aucune donnée disponible",
            "search": "Chercher:",
            "zeroRecords": "Aucun enregistrements correspondants trouvés",
            "paginate": {
                "first": "Premier",
                "last": "Dernier",
                "next": "Suivant",
                "previous": "Précédent"
            },
        }
    });
    var data = <?php echo $details; ?>;
    $('#tabaffiche').DataTable({
        data: data,
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },
            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        columns: [
            {data: 'Ref_', title: '<b>N° Dossier </b>'},
            {data: 'RensAge_', title: '<b>Age </b>'},
            {data: 'RensSexe', title: '<b>Sexe </b>'},
            {data: 'OuvrDat_', title: "<b>Date d'inscription </b>"},
            {data: 'Nbrcons', title: "<b>Nombre de consultation </b>"},
            {data: 'derncons', title: "<b>Date Dernière Consultation  </b>"},
            {data: 'Arv_Desi', title: "<b>Protocole ARV en cours </b>"},
            {data: 'MediSeroTyp_', title: "<b>Type de sérologie </b>"},
            /* { data: 'RensChrg',title:"<b>Prise en charge </b>" },*/
            {data: 'RensTel_', title: "<b>Telephone </b>"},
            {data: 'Dat_initImc_info', title: "<b>Date Imc Initial</b>"},
            {data: 'initImc_info', title: "<b>Imc initial</b>"},
            {data: 'Dat_dernImc_info', title: "<b>Date Dernier Imc </b>"},
            {data: 'dernImc_info', title: "<b>Dernier Imc </b>"},
            {data: 'Dat_initConc_info', title: "<b>Date Stade OMS Initial</b>"},
            {data: 'initConc_info', title: "<b>Stade OMS initial</b>"},
            {data: 'Dat_dernConc_info', title: "<b>Date Dernier Stade OMS </b>"},
            {data: 'dernConc_info', title: "<b>Dernier Stade OMS </b>"},
        ],
    });
    /* $('#detailbtn').on('click', function () { alert('sdf');
     document.getElementById('testinnn').innerHTML = document.getElementById('tabaffiche').innerHTML;
     //  document.getElementById('tabaffiche').innerHTML;
     });*/
</script>
