<?php
$title = 'Detail';
$this->headTitle($title);
?>
<div class="modal-dialog modal-lg">  
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?php echo $this->escapeHtml($title); ?></h4>
        </div>
        <div class="modal-body">
            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Acti</th>
                        <th>Dat_</th>
                        <th>Nota</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?php echo $this->escapeHtml($comm->Acti); ?></td>
                        <td><?php echo $this->escapeHtml($comm->Dat_); ?></td>
                        <td><?php echo $this->escapeHtml($comm->Nota); ?></td>
                    </tr> 
                </tbody>
            </table>
            <!-- /.table-responsive -->
        </div>
        <div class="modal-footer">
            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example1">
                <thead>
                    <tr>
                        <th colspan="2">Participants à cette activité</th>
                    </tr>
                </thead><tbody>
                    <tr>
                        <td>
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example2">
                                <thead>
                                    <tr>
                                        <th>N° Dossier</th>
                                        <th>Nom et prénoms</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <td colspan="3">
                                            <div class="form-group form-group-sm">
                                                <label class="control-label col-sm-3">
                                                    <?php echo $this->formLabel($DossForm->get('Ref_doss')); ?>
                                                </label>
                                                <div class="col-sm-7"> 
                                                    <?php echo $this->formInput($DossForm->get('Ref_doss'));
                                                    echo $this->formElementErrors($DossForm->get('Ref_doss')); ?>
                                                </div>
                                                <a title="Ajouter Dossier" class="btn btn-primary col-sm-2" href="#" id="adddoss">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                </a> 
                                            </div>
                                        </td>
                                    </tr>
                                </tfoot>
                                <tbody id="doss">
                                    <?php foreach ($Doss as $dos) : ?>
                                        <tr id='tr<?php echo $dos->Nume;?>'>
                                            <td><?php echo $this->escapeHtml($dos->Ref_); ?></td>
                                            <td><?php echo $this->escapeHtml($dos->Nom_ . ' ' . $dos->Pnom); ?></td>
                                            <td>
                                                <a title="Supprimer" class="btn btn-sm btn-danger" href="#" id="<?php echo $dos->Nume;?>">
                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                </a> 
                                            </td>
                                        </tr> 
                                    <?php endforeach; ?>
                                </tbody>                
                            </table>
                            <!-- /.table-responsive -->
                        </td>
                        <td>
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example3">
                                <thead>
                                    <tr>
                                        <th>N° OEV</th>
                                        <th>Nom et prénoms</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <td colspan="3">
                                            <div class="form-group form-group-sm">
                                                <label class="control-label col-sm-3">
                                                    <?php echo $this->formLabel($OevForm->get('Ref_oev')); ?>
                                                </label>
                                                <div class="col-sm-7"> 
                                                    <?php echo $this->formInput($OevForm->get('Ref_oev'));
                                                    echo $this->formElementErrors($OevForm->get('Ref_oev')); ?>
                                                </div>
                                                <a title=" Ajouter OEV" class="btn btn-primary col-sm-2" href="#" id="addoev">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                </a> 
                                            </div>
                                        </td>
                                    </tr>
                                </tfoot>
                                <tbody id="oev">
                                    <?php foreach ($Oev_ as $oev) : ?>
                                        <tr id='tr<?php echo $oev->Nume;?>'>
                                            <td><?php echo $this->escapeHtml($oev->Ref_); ?></td>
                                            <td><?php echo $this->escapeHtml($oev->Nom_ . ' ' . $oev->Pnom); ?></td>
                                            <td>
                                                <a title="Supprimer" class="btn btn-sm btn-danger" href="#" id="<?php echo $oev->Nume;?>">
                                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                </a> 
                                            </td>
                                        </tr> 
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                        </td>
                    </tr> 
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="infoscomm" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
</div>

<script type="text/javascript">
    
    $('#infoscomm').on('hidden.bs.modal', function () {
        document.getElementById('infoscomm').innerHTML = "";
        $('#infoscomm').removeData('bs.modal');
    });
    
    $('#adddoss').on('click', function () {
            var Ref_doss = document.getElementById('Ref_doss').value;
            if (Ref_doss != '') {
                var Comm = <?php echo $comm->Nume; ?>;
                var tr = document.createElement('tr');
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url('communaute', array('action' => 'Ajax')); ?>',
                    dataType: 'json',
                    data: {'Nume': Ref_doss,'Comm': Comm},
                    success: function (data) {
                        tr.innerHTML = '<td>'+data.Ref_+'</td><td>'+data.Nom_+' '+data.Pnom+'</td><td></td>';
                        var table = document.getElementById('doss');
                        table.appendChild(tr);
                    },
                    error: function () {
                        alert('Erreur Server');
                    }
                });
            } else {
                alert("saisir numéro de dossier");
            }
        });
        
    $('#addoev').on('click', function () {
            var Ref_oev = document.getElementById('Ref_oev').value;
            if (Ref_oev != '') {
                var Comm = <?php echo $comm->Nume; ?>;
                var tr = document.createElement('tr');
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url('communaute', array('action' => 'Ajax2')); ?>',
                    dataType: 'json',
                    data: {'Nume': Ref_oev,'Comm': Comm},
                    success: function (data) {
                        tr.innerHTML = '<td>'+data.Ref_+'</td><td>'+data.Nom_+' '+data.Pnom+'</td><td></td>';
                        var table = document.getElementById('oev');
                        table.appendChild(tr);
                    },
                    error: function () {
                        alert('Erreur Server');
                    }
                });
            } else {
                alert("saisir numéro de oev");
            }
        });
        
    $('.btn.btn-sm.btn-danger').on('click', function () {
        var id = this.id;
        var tr = document.getElementById('tr'+id);
            $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url('communaute', array('action' => 'delcommdoss')); ?>',
                    dataType: 'json',
                    data: {'Nume': id,},
                    success: function () {
                        tr.remove();
                    },
                    error: function () {
                        alert('Erreur Server2');
                    }
                });
        });

</script>

