<?php
$title = 'PROFIL DES PATIENTS ENREGISTRES';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'profilpatient')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
//->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
//->prependFile($this->basePath('themes/datas/js/chartist-pie.js'))
// ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
// ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/data.js'))
// ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right">
                    <div class="form-group">
                        <div class="col-sm-8">
                            <?php
                            echo $this->formInput($form->get('daterappmoi'));
                            echo $this->formElementErrors($form->get('daterappmoi'));
                            ?>
                        </div>
                        <div class="col-sm-3">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="profil">
                        <thead>
                            <tr>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($tabprofil as $tabprof) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($tabprof['titre']); ?></td>

                                    <td>
                                        <?php
                                        if ($tabprof['titre'] === 'File active')
                                            echo '<a title="Voir detail"  data-toggle="modal" title="Détails" href="#details">'
                                            . "<span class='label label-primary'>" . $this->escapeHtml($tabprof['valeur']) . "</span></a>";
                                        else
                                        if ($tabprof['titre'] === 'Nombre total de patients inscrits au CTA à la fin du mois')
                                            echo '<a title="Voir detail"  data-toggle="modal" title="Détails" href="#dossdetails">'
                                            . "<span class='label label-primary'>" . $this->escapeHtml($tabprof['valeur']) . "</span></a>";
                                        else
                                            echo $this->escapeHtml($tabprof['valeur']);
                                        ?>
                                    </td>
                                </tr> 
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <br/>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<div class="modal fade" id="details" tabindex="-1" role="dialog" aria-labelledby="details" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">File active - Détails</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="examples col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche">
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="dossdetails" tabindex="-1" role="dialog" aria-labelledby="details" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Patient - Détails</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="examples col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche1">
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<script>
    $('#profil').DataTable({
        dom: 'Bfrtip',
        "buttons": [
            {
                extend: 'collection',
                text: 'Exporter la liste',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copier',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa fa-print"></i> Imprimer',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'excel',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        className: 'btn btn-primary',
                    }
                ],
                className: 'btn btn-primary',
            }
        ],
        "ordering": false,
        "searching": false,
        "paging": false,
        "info": false,
        language: {
            buttons: {
                copyTitle: 'Ajouté au presse-papiers',
                /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                copySuccess: {
                    _: '%d lignes copiées',
                    1: '1 ligne copiée'
                }
            },
            "emptyTable": "aucune donnée disponible",
            "search": "Chercher:",
            "zeroRecords": "Aucun enregistrements correspondants trouvés",
            "paginate": {
                "first": "Premier",
                "last": "Dernier",
                "next": "Suivant",
                "previous": "Précédent"
            },
        }
    });
    var data = <?php echo $details; ?>;
    $('#tabaffiche').DataTable({
        data: data,
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },
            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'excel',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        columns: [
            {data: 'Ref', title: '<b>N° Dossier </b>'},
            {data: 'RensAge_', title: '<b>Age </b>'},
            {data: 'RensSexe', title: '<b>Sexe </b>'},
            {data: 'Arv_Desi', title: '<b> Protocole ARV en cours </b>'},
            {data: 'Visit', title: '<b>Date Derniere visite </b>'},
        ],
    });

    var data1 = <?php echo $dossdetails; ?>;
    $('#tabaffiche1').DataTable({
        data: data1,
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },
            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'excel',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        columns: [
            {data: 'Ref', title: '<b>N° Dossier </b>'},
            {data: 'RensAge_', title: '<b>Age </b>'},
            {data: 'RensSexe', title: '<b>Sexe </b>'},
            {data: 'OuvrDat_', title: '<b>Date d\'ouverture </b>'},
        ],
    });
   
</script>
