<?php
$title = 'SUIVI BIOLOGIQUE';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'suivibio')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
        ->prependFile($this->basePath('themes/datas/js/chartist-pie.js'))
        ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="panel panel-primary-border-top">
    <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right" style="margin-right: 15px;">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datedeb'));
                            echo $this->formElementErrors($form->get('datedeb'));
                            ?>
                        </div>
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datefin'));
                            echo $this->formElementErrors($form->get('datefin'));
                            ?>
                        </div>
                        <div class="col-sm-2">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        
       <div class="row">
                <div class="col-md-12">
                    <div class="suivbiol" data-highcharts-chart="7">
                    </div>
                </div>
            </div>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="suivibiol">
                    <thead>
                        <tr>
                            <th>Analyses biologiques effectuées au CTA</th>
                            <th>Nombre</th>
                            <th>Pourcentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabbiol as $k=>$tabbio) :?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php 
                                if($k=='Total')
                                echo '<a title="Voir detail"  data-toggle="modal" title="Détails" href="#biodetails">'
                                            ."<span class='label label-primary'>".$this->escapeHtml($tabbio['valeur'])."</span></a>";
                                else
                                echo $this->escapeHtml($tabbio['valeur']); 
                                ?></td>
                                
                                <td><?php echo $this->escapeHtml($tabbio['pourcentage']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
        
    </div>
</div>

<?php echo $this->form()->closeTag() ?>
<div class="modal fade" id="biodetails" tabindex="-1" role="dialog" aria-labelledby="details" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Biologie- Détails</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="examples col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche">
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
           $('#suivibiol').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Rechercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
           $('#analhorscta').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
        
    var tabbiol = <?php echo json_encode($tabbiol); ?>;
    function extract(tabdepis) {
        var i= 0;
        var result = Array();
        for (var indice in tabdepis)
        {   
            if(indice!='Total')   { 
                result[i] = Array();
                result[i][0] = indice;
                result[i][1] = parseInt(tabdepis[indice]['valeur']);
                i++;
            }
        }
        return result;
    }
    $(function () {
   
        var result = extract(tabbiol);
       $('.suivbiol').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
        title: {
            text: 'Répartition des analyses biologiques'
        },
         credits: {
            enabled: false
        },
        tooltip: {
            pointFormat: '{point.name} : <b>{point.percentage:.0f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Product share',
            data: result,
           /* data: [
                {
                    name: 'Numération de formule sanguine',
                    y: parseInt(result['Numération de formule sanguine']),
                    sliced: true
                },
                {
                    name: 'Glycémie',
                    y: parseInt(result['Glycémie']),
                    sliced: true
                }, 
                {
                    name: 'Créatinine',
                    y: parseInt(result['Créatinine']),
                    sliced: true
                },
                {
                    name: 'Dépistage',
                    y: parseInt(result['Dépistage']),
                    sliced: true
                },
                {
                    name: 'Hépatite B',
                    y: parseInt(result['Hépatite B']),
                    sliced: true
                },
                {
                    name: 'ALAT',
                    y: parseInt(result['ASAT']),
                    sliced: true
                },
                {
                    name: 'CD4',
                    y: parseInt(result['CD4']),
                    sliced: true
                },
                {
                    name: 'Cholesterol',
                    y: parseInt(result['Cholesterol']),
                    sliced: true
                },
                {
                    name: 'Triglycéride',
                    y: parseInt(result['Triglycéride']),
                    sliced: true
                },
                {
                    name: 'Urée',
                    y: parseInt(result['Urée']),
                    sliced: true
                },
                {
                    name: 'Groupe sanguin / Rhésus',
                    y: parseInt(result['Groupe sanguin / Rhésus']),
                    sliced: true
                },
                {
                    name: 'Autres',
                    y: parseInt(result['Autres']),
                    sliced: true
                }
            ]*/
        }]
    });
    });
    
    var data = <?php echo $biodetails; ?>;
        $('#tabaffiche').DataTable({
        data: data,
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },
            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'excel',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        columns: [
            {data: 'Ref_', title: '<b>N° Dossier </b>'},
            {data: 'RensAge_', title: '<b>Age </b>'},
            {data: 'RensSexe', title: '<b>Sexe </b>'},
            {data: 'Arv_Desi', title: '<b> Protocole ARV en cours </b>'},
            {data: 'Nfs_', title: '<b>Numération de formule sanguine </b>'},
            {data: 'Bi00', title: '<b>Glycémie </b>'},
            {data: 'Bi01', title: '<b>Créatinine </b>'},
            {data: 'Ser0', title: '<b>Dépistage</b>'},
            {data: 'Ser2', title: '<b>Hépatite B </b>'},
            {data: 'Bi02', title: '<b>ALAT </b>'},
            {data: 'Bi03', title: '<b>ASAT </b>'},
            {data: 'CD4_', title: '<b>CD4 </b>'},
            {data: 'Bi04', title: '<b>Cholesterol </b>'},
            {data: 'Bi05', title: '<b>Triglycéride </b>'},
            {data: 'Bi11', title: '<b>Urée </b>'},
            {data: 'Au01', title: '<b>Groupe sanguin / Rhésus</b>'},
        ],
    });
  
    
    });
</script>