<?php
$title = 'SUIVI NUTRITIONNEL';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'suivinutri')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
        ->prependFile($this->basePath('themes/datas/js/chartist-pie.js'))
        ->prependFile($this->basePath('themes/datas/js/highcharts-data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/modules/data.js'))
        ->prependFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'));
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right">
                    <div class="form-group">
                        <div class="col-sm-4">
                            <?php
                            echo $this->formInput($form->get('datedeb'));
                            echo $this->formElementErrors($form->get('datedeb'));
                            ?>
                        </div>
                        <div class="col-sm-4">
                            <?php
                            echo $this->formInput($form->get('datefin'));
                            echo $this->formElementErrors($form->get('datefin'));
                            ?>
                        </div>
                        <div class="col-sm-4">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
       
        <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabsuivinutri">
                    <thead>
                        <tr>
                            <th>Distribution de Kits nutritionnels</font></th>
                            <th>Enfants de moins de 15 ans</th>
                            <th>Adultes</th>
                            <th>Total</th>
                            <th>Pourcentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabsuivnutri as $k=> $tabsuivnutr) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivnutr['enf']); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivnutr['adlt']); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivnutr['Total']); ?></td>
                                <td><?php echo $this->escapeHtml($tabsuivnutr['Pourcentage']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
           
        <br/>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabsuivimc">
                    <thead>
                        <tr>
                            <th>IMC des adultes et adolescents 16 et plus de la file active</th>
                            <th>Nombre</th>
                            <th>Pourcentage</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabimc as $k => $tabim) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabim['valeur']); ?></td>
                                <td><?php echo $this->escapeHtml($tabim['pourcentage']); ?></td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <br/>
            <div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabsuivpsy">
                    <thead>
                        
                        <tr>
                            <th></th>
                            <th></th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabnutristat as $k =>$tabnutrista) : ?>
                        
                            <tr>
                                <td><?php echo $this->escapeHtml($k); ?></td>
                                <td><?php echo $this->escapeHtml($tabnutrista['valeur']); ?></td>
                               </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <br/>
            <!--<div class="table-responsive">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="consind">
                    <thead>
                        <tr>
                            <th><font color="red">Consultations individuelles<font></th>
                            <th>Nombre</th>
                            <th>Pourcentage</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($tabconsindivi as $tabconsindiv) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($tabconsindiv['titre']); ?></td>
                                <td><?php echo $this->escapeHtml($tabconsindiv[1]); ?></td>
                                <td><?php echo $this->escapeHtml($tabconsindiv[2]); ?></td>
                                
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div> -->
            <br/>
    </div>
    <!-- /.panel-body -->
    <div class="panel-footer">
        
    </div>
</div>

<?php echo $this->form()->closeTag() ?>

<script>
    $(document).ready(function () {
           $('#tabsuivimc').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
           $('#tabsuivinutri').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
           $('#consind').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'collection',
                    text: 'Exporter la liste',
                    buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i> Copier',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa fa-print"></i> Imprimer',
                            className: 'btn btn-primary',
                        },
                        {
                            extend: 'excel',
                            text: '<i class="fa fa-file-excel-o"></i> Excel',
                            className: 'btn btn-primary',
                        }
                    ],
                    className: 'btn btn-primary',
                }
            ],
            "ordering": false,
            language: {
                buttons: {
                    copyTitle: 'Ajouté au presse-papiers',
                    /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                    copySuccess: {
                        _: '%d lignes copiées',
                        1: '1 ligne copiée'
                    }
                },
                "emptyTable": "aucune donnée disponible",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
            }
        });
          
    });
</script>