<?php
$title = 'PATIENTS TRANFERES';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('analyse', array('action' => 'transpatient')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/css/buttons.dataTables.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/csk.css'))
?>
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Nume'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
             <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right" style="margin-right: 15px;">
                    <div class="form-group">
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datedeb'));
                            echo $this->formElementErrors($form->get('datedeb'));
                            ?>
                        </div>
                        <div class="col-sm-5">
                            <?php
                            echo $this->formInput($form->get('datefin'));
                            echo $this->formElementErrors($form->get('datefin'));
                            ?>
                        </div>
                        <div class="col-sm-2">
                            <button type="submit" name="submit" id="submit" class="btn btn-primary">Lancer</button>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="transtable">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($transfpat as $k => $transfpa) : ?>
                                        <tr>
                                            <td><?php echo $this->escapeHtml($k); ?></td>
                                            <td>
                                                <?php
                                                    if ($k === 'Nombre Total Patients transferés')
                                                        echo '<a title="Voir detail"  data-toggle="modal" title="Détails" href="#transdetails">'
                                                        . "<span class='label label-primary'>" . $this->escapeHtml($transfpa['valeur']) . "</span></a>";
                                                    else
                                                        echo $this->escapeHtml($transfpa['valeur']);
                                                    ?>
                                            </td>
                                        </tr> 
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <br/>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<div class="modal fade" id="transdetails" tabindex="-1" role="dialog" aria-labelledby="details" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Patient - Détails</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="examples col-md-12">
                        <div class="table-responsive">
                            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="tabaffiche2">
                            </table>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<script>
     $('#transtable').DataTable({
        dom: 'Bfrtip',
        "buttons": [
            {
                extend: 'collection',
                text: 'Exporter la liste',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copier',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa fa-print"></i> Imprimer',
                        className: 'btn btn-primary',
                    },
                    {
                        extend: 'excel',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        className: 'btn btn-primary',
                    }
                ],
                className: 'btn btn-primary',
            }
        ],
        "ordering": false,
        "searching": false,
        "paging": false,
        "info": false,
        language: {
            buttons: {
                copyTitle: 'Ajouté au presse-papiers',
                /*copyKeys: 'Appuyez sur <i>ctrl</i> ou <i>\u2318</i> + <i>C</i> pour copier les données du tableau à votre presse-papiers. <br><br>Pour annuler, cliquez sur ce message ou appuyez sur Echap.',*/
                copySuccess: {
                    _: '%d lignes copiées',
                    1: '1 ligne copiée'
                }
            },
            "emptyTable": "aucune donnée disponible",
            "search": "Chercher:",
            "zeroRecords": "Aucun enregistrements correspondants trouvés",
            "paginate": {
                "first": "Premier",
                "last": "Dernier",
                "next": "Suivant",
                "previous": "Précédent"
            },
        }
    });
    var data2 = <?php echo $transdetail; ?>;
    $('#tabaffiche2').DataTable({
        data: data2,
        dom: 'Blfrtip',
        "buttons": [
            {
                extend: 'copyHtml5',
                text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                className: 'btn btn-info btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                }
            },
            {
                extend: 'csvHtml5',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'excel',
                text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                className: 'btn btn-success btn-outline btn-rounded',
                key: {
                    key: 'c',
                    altKey: true
                },
                customize: function (csv) {
                    return "\t\tAMNIR ECHIVA\n\t\tConsultations Médicales\n\n" + csv;
                }
            },
            {
                extend: 'print',
                text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                message: 'Amnir Echiva',
                className: 'btn btn-danger btn-outline btn-rounded',
                key: {
                    key: 'p',
                    altKey: true
                }
            },
        ],
        columns: [
            {data: 'Ref', title: '<b>N° Dossier </b>'},
           /* {data: 'RensAge_', title: '<b>Age </b>'},
            {data: 'RensSexe', title: '<b>Sexe </b>'},
            {data: 'OuvrDat_', title: '<b>Date d\'ouverture </b>'},
            {data: 'Arv_Desi', title: '<b>Protocole ARV </b>'},*/
            {data: 'TransDat_', title: '<b>Date de Transfert </b>'},
            {data: 'Source', title: '<b>Source </b>'},
            {data: 'Destination', title: '<b>Destination </b>'},
        ],
    });
</script>
