<?php
$title = 'Orphelins et enfants vulnérables';
$this->headTitle($title);
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
?>
<style>
    div.dataTables_length{
position:relative;
float:left;
}
.space{
    margin-right:10px;
}
</style>
<!-- row -->
<?php
echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                 <?php if ($this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'add')  &&($prefixe===$prefixeagent)) { ?>
                <div class="btn-group pull-right">
                    <a  title="Nouveau" class="btn  btn-primary btn-outline btn-rounded" href="<?php echo $this->url('oev', array('action' => 'add')); ?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Créer un nouveau OEV
                    </a>
                </div>
                 <?php } ?>
            </div>            
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                    <thead>
                        <tr>

                            <th><b>N° Dossier</b></th>
                            <th><b>Nom</b></th>
                            <th><b>Prenom</b></th>
                            <th><b>Sexe</b></th>
                            <th><b>Age</b></th>
                            <th><b>Situation Sanitaire</b></th>
                            <?php if ($this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'edit') ||$this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'delete') ) { ?>
                            <th><b>Action</b></th>
                            <?php } ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($oevs as $oev) : ?>
                            <tr>
                                <td> <?php echo $this->escapeHtml($oev->Ref_); ?>
                                </td>

                                <td><?php echo $this->escapeHtml($oev->Nom_); ?></td>
                                <td><?php echo $this->escapeHtml($oev->Pnom); ?></td>
                                <td><?php
                                    if ($oev->Sexe === '1')
                                        echo $this->escapeHtml("Masculin");
                                    else
                                    if ($oev->Sexe === '2')
                                        echo $this->escapeHtml("Feminin");
                                    else
                                        echo $this->escapeHtml("");
                                     
                                    ?></td>
                                <td><?php echo $this->escapeHtml($oev->Age_); ?></td>
                                <td><?php echo $this->escapeHtml($oev->Sani); ?></td>
                                <td>
                                    <?php if ($this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'edit') ) { ?>
                                    <a title="Modifier" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('oev', array('action' => 'edit', 'Nume' => $oev->Nume)); ?>">
                                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    </a>
                                     <?php } ?>
                                    <?php if ($this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'delete') ) { ?>
                                    <a data-toggle="modal" data-target="#delete" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('oev', array('action' => 'delete', 'Nume' => $oev->Nume)); ?>">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    </a>
                                     <?php } ?>
                                </td>
                            </tr> 
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">
                <div class="row">
                    <div class='col-sm-6'>

                    </div>
                    <?php if ($this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'add')  &&($prefixe===$prefixeagent)) { ?>
                    <div class="col-sm-2 col-sm-offset-4">
                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('oev', array('action' => 'add')); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Créer un nouveau OEV
                        </a>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.panel -->

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Oev",
                "infoEmpty": "Affichage 0 à 0 de 0 OEV",
                "infoFiltered": "(Filtré de _MAX_ OEV totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ OEV",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
    });

</script>