<?php
$title = 'ajouter communaute';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('communaute', array('action' => 'add',)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<div class="modal-dialog modal-lg">  
    <div class="modal-content">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formHidden($form->get('Nume')); ?>
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"><?php echo $this->escapeHtml($title); ?></h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <label class="control-label col-sm-3">
                            <?php echo $this->formLabel($form->get('Dat_')); ?>
                        </label>
                        <div class="col-sm-9">
                            <?php
                            echo $this->formInput($form->get('Dat_'));
                            echo $this->formElementErrors($form->get('Dat_'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">
                            <?php echo $this->formLabel($form->get('Acti')); ?>
                        </label>
                        <div class="col-sm-9">
                            <?php
                            echo $this->formSelect($form->get('Acti'));
                            echo $this->formElementErrors($form->get('Acti'));
                            ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3">
                            <?php echo $this->formLabel($form->get('Nota')); ?>
                        </label>
                        <div class="col-sm-9">
                            <?php
                            echo $this->formInput($form->get('Nota'));
                            echo $this->formElementErrors($form->get('Nota'));
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <?php echo $this->formInput($form->get('submit')) . ' ' . $this->formInput($form->get('rest')); ?>
        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>
