<?php
$title = 'Communaute';
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
?>

<!-- row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right">
                    <a data-toggle="modal" data-target="#infos" title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'add')); ?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Communaute
                    </a>                            
                </div>

                <div class="clearfix"></div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Activité</th>
                                <th>Date</th>
                                <th>Commentaire</th>
                                <th>Detail</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($comms as $entr) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($entr->Acti); ?></td>
                                    <td><?php echo $this->escapeHtml($entr->Dat_); ?></td>
                                    <td><?php echo $this->escapeHtml($entr->Nota); ?></td>
                                    <td>
                                        <a  title="Detail" class="btn btn-sm btn-info btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'more', 'Nume' => $entr->Nume)); ?>">
                                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                        </a>
                                        <a title="Modifier" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'edit', 'Nume' => $entr->Nume)); ?>">
                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        </a>
                                        <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'delete', 'Nume' => $entr->Nume)); ?>">
                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        </a>
                                    </td>
                                </tr> 
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">
                <div class="row">
                    <div class='col-sm-10'>
                        <form method="post" class="form-inline" action="<?php echo $this->url('communaute'); ?>" id="formday">
                            <div class="form-group">
                                De : 
                                <span class="input-group date" id="datetimepicker1">
                                    <input type='text' class="form-control" name="daymin" id="hiddenFieldID1" value="<?php echo $this->escapeHtml($this->daymin); ?>"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </span>
                                à : <span class="input-group date" id="datetimepicker2">
                                    <input type='text' class="form-control" name="daymax" id="hiddenFieldID2" value="<?php echo $this->escapeHtml($this->daymax); ?>"/>
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </span>
                                <span class="input-group">
                                    <input type="submit" class="btn btn-sm btn-primary btn-outline btn-rounded" value="Ok">
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-2">
                        <div class="btn-group pull-right">
                            <a data-toggle="modal" data-target="#infos" title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'add')); ?>">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Communaute
                            </a>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.panel -->
    </div>
</div>


<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            dom: 'Bfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ entrées",
                "infoEmpty": "Affichage 0 à 0 de 0 entrées",
                "infoFiltered": "(Filtré de _MAX_ entrées totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Entrées",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Chercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
    });
</script>
