 <?php
$title = 'Communauté';
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
?>
<style>
    div.dataTables_length{
position:relative;
float:left;
}
.space{
    margin-right:10px;
}
</style>

<!-- row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <?php if ($this->IsAllowed()->isAllowed('Communaute\Controller\Communaute', 'add')) { ?>
                <div class="btn-group pull-right">
                    <a  title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'add')); ?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Communauté
                    </a>                            
                </div>
                <?php } ?>
                <div class="clearfix"></div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <?php echo $this->dataTable('communautedatatable')->renderHtml(); ?>
                    <!-- /.table-responsive -->
                </div>                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12">
                        <div class='pull-left'>
                            <form  class="form-inline">
                                <div class="form-group">
                                    De : 
                                    <span class="input-group date">
                                        <input type='date' class="form-control" name="daymin" id="daymin" value="<?php echo $daymin; ?>" />
                                    </span>
                                    à : <span class="input-group date">
                                        <input type='date' class="form-control" name="daymax" id="daymax" value="<?php echo $daymax; ?>"/>
                                    </span>
                                </div>
                            </form>
                        </div>
                        <?php if ($this->IsAllowed()->isAllowed('Communaute\Controller\Communaute', 'add')) { ?>
                        <div class="btn-group pull-right">
                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('communaute', array('action' => 'add')); ?>">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Communauté
                            </a>                            
                        </div>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!-- /.panel -->
    </div>
</div>


<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        var dataTable = $('#communautedb').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                dataType: 'json',
                url: '<?php echo $this->url('communaute', array('action' => 'data')); ?>',
                data: function (data) {
                    data.daymin = $('#daymin').val();
                    data.daymax = $('#daymax').val();
                },
            },
            deferRender: true,
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            "responsive": true,
            language: {
                "decimal": "",
                "emptyTable": "aucune communauté disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ communautés",
                "infoEmpty": "Affichage 0 à 0 de 0 communautés",
                "infoFiltered": "(Filtré de _MAX_ communautés totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Communautés",
                "loadingRecords": "<div id='loader'></div>",
                "processing": "<div id='loader'></div>",
                "search": "<b>Rechercher : </b>",
                "zeroRecords": "Aucun communautés correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#daymin').on('change', function (event) {
            dataTable.draw();
        });
        $('#daymax').on('change', function (event) {
            dataTable.draw();
        });

    });
</script>
