<?php
$title = "Liste de participants";
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'));
?>
<style>
    div.dataTables_length{
        position:relative;
        float:left;
    }
</style>
<div class="panel panel-primary-border-top">
    <div class="panel-heading">
        <h4 class="panel-title"><?php echo $this->escapeHtml($title); ?>
            <a href="<?php echo $this->url('communaute'); ?>" class="btn btn-warning btn-outline btn-rounded pull-right">Fermer</a></h4>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                <thead>
                    <tr>
                        <th><b>Activité</b></th>
                        <th><b>Date</b></th>
                        <th><b>Commentaire</b></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?php echo $this->escapeHtml($comm['Acti']); ?></td>
                        <td><?php echo substr($this->escapeHtml($comm['Dat_']), 0, -9); ?></td>
                        <td><?php echo $this->escapeHtml($comm['Nota']); ?></td>
                    </tr> 
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Participants à cette activité
                    </div>
                    <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#Dossiers" data-toggle="tab">Dossiers</a></li>
                            <li><a href="#Oev" data-toggle="tab">Dossiers OEV</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="Dossiers">
                                <div class="panel panel-primary-border-top">
                                    <div class="panel-heading clearfix">

                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="commdossdatatable">
                                            <thead>
                                                <tr>
                                                    <th><b>N° Dossier</b></th>
                                                    <th><b>Age</b></th>
                                                    <th><b>Sexe</b></th>
                                                    <th><b>Commentaire</b></th>
                                                    <th><b>Action</b></th>
                                                </tr>
                                            </thead>
                                            <tbody id="doss">
                                                <?php
                                                $t[1] = "Masculin";
                                                $t[2] = "Feminin";
                                                foreach ($Doss as $dos) :
                                                    ?>
                                                    <tr id='tr<?php echo $dos['Nume']; ?>'>
                                                        <td><?php echo $this->escapeHtml($dos['Ref_']); ?></td>
                                                        <td><?php echo $this->escapeHtml($dos['Age_']); ?></td>
                                                        <td><?php
                                                            $sexe = "";
                                                            if (isset($t[$dos['Sexe']]))
                                                                $sexe = $t[$dos['Sexe']];
                                                            echo $sexe;
                                                            ?></td>
                                                        <td><?php echo $this->escapeHtml($dos['Motif']); ?></td>
                                                        <td>
                                                            <a title="Supprimer" class="btn btn-sm btn-danger" href="#" id="<?php echo $dos['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                            </a> 
                                                        </td>
                                                    </tr> 
                                                <?php endforeach; ?>

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td>
                                                        <div class="form-group form-group-sm">
                                                            <label class="control-label col-sm-3">
                                                                <?php echo $this->formLabel($DossForm->get('Ref_doss')); ?>
                                                            </label>
                                                            <div class="col-sm-7"> 
                                                                <?php
                                                                echo $this->formInput($DossForm->get('Ref_doss'));
                                                                echo $this->formElementErrors($DossForm->get('Ref_doss'));
                                                                ?>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <div class="font-input">
                                                            <div>
                                                                <input id="Except_doss" name="Except_doss" type="Checkbox" class="with-font" required="" value="1" >
                                                                <label for="Except_doss">Exception</label>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td></td>
                                                    <td>
                                                        <div class="form-group form-group-sm" id="div_motif" style="display:none">
                                                            <div class="col-sm-12"> 
                                                                <?php
                                                                echo $this->formInput($DossForm->get('Motif'));
                                                                echo $this->formElementErrors($DossForm->get('Motif'));
                                                                ?>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <a title="Ajouter Dossier" class="btn btn-primary" href="#" id="adddoss">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                        </a>
                                                    </td>
                                                </tr> 
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="Oev">
                                <div class="panel panel-primary-border-top">
                                    <div class="panel-heading clearfix">

                                    </div>
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="commoevdatatable">
                                            <thead>
                                                <tr>
                                                    <th><b>Code enfant</b></th>
                                                    <th><b>Sexe</b></th>
                                                    <th><b>Age</b></th>
                                                    <th><b>Code tuteur</b></th>
                                                    <th><b>Montant</b></th>
                                                    <th><b>Signature</b></th>
                                                    <th><b>Commentaire</b></th>
                                                    <th><b>Action</b></th>
                                                </tr>
                                            </thead>
                                            <tbody id="oev">
                                                <?php
                                                $t[1] = "Masculin";
                                                $t[2] = "Feminin";
                                                foreach ($Oev_ as $oev) :
                                                    ?>
                                                    <tr id='tr<?php echo $oev->Nume; ?>'>
                                                        <td><?php echo $this->escapeHtml($oev->Ref_); ?></td>
                                                        <td><?php
                                                            $sexe = "";
                                                            if (isset($t[$oev->Sexe]))
                                                                $sexe = $t[$oev->Sexe];
                                                            echo $sexe;
                                                            ?>
                                                        </td>
                                                        <td><?php echo $this->escapeHtml($oev->Age_); ?></td>
                                                        <td><?php echo $this->escapeHtml($oev->Tuteur); ?></td>
                                                        <td><?php echo $this->escapeHtml($oev->Montant); ?></td>
                                                        <td></td>
                                                        <td></td>
                                                        <td> 
                                                            <a title="Supprimer" class="btn btn-sm btn-danger" href="#" id="<?php echo $oev->Nume; ?>">
                                                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                            </a>
                                                        </td>
                                                    </tr> 
                                                <?php endforeach; ?>

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <td>
                                                        <div class="form-group form-group-sm">
                                                            <label class="control-label col-sm-3">
                                                                <?php echo $this->formLabel($OevForm->get('Ref_oev')); ?>
                                                            </label>
                                                            <div class="col-sm-7"> 
                                                                <?php
                                                                echo $this->formInput($OevForm->get('Ref_oev'));
                                                                echo $this->formElementErrors($OevForm->get('Ref_oev'));
                                                                ?>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td></td>
                                                    <td>
                                                         <div class="font-input">
                                                            <div>
                                                                <input id="Except_oev" name="Except_oev" type="Checkbox" class="with-font" required="" value="1" >
                                                                <label for="Except_oev">Exception</label>
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td></td>
                                                    <td></td>
                                                    <td></td>
                                                    <td>
                                                        <div class="form-group form-group-sm" id="div_motifoev" style="display:none">
                                                            <div class="col-sm-12"> 
                                                                <input name="Motifoev" type="text" class="form-control" id="Motifoev" value="">
                                                            </div>
                                                        </div>
                                                    </td>
                                                    <td>
                                                        <a title=" Ajouter OEV" class="btn btn-primary" href="#" id="addoev">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                                        </a>
                                                    </td>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var tabdoubledoss = Array();
        var doss = <?php echo json_encode($Doss); ?>;
        //settabdouble(doss);
        var commp = <?php echo json_encode($commprec); ?>;
        var tabp = conversion(commp);
        var tabdoubleoev = Array();


        var commdossdatatable = $('#commdossdatatable').DataTable({
            responsive: true,
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'excel',
                    text: '<i class="fa fa-file-excel-o"></i> Excel',
                    titleAttr: 'Export to Excel',
                    className: 'btn btn-success btn-outline btn-rounded',
                    exportOptions: {
                        columns: [0, 1, 2]
                    }

                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span>Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'btn btn-danger btn-outline btn-rounded',
                    exportOptions: {
                        columns: [0, 1, 2]
                    }
                },
            ],
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Dossiers",
                "infoEmpty": "Affichage 0 à 0 de 0 Dossiers",
                "infoFiltered": "(Filtré de _MAX_ Dossiers totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Dossiers",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });

        var commoevdatatable = $('#commoevdatatable').dataTable({
            responsive: true,
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'excel',
                    text: '<i class="fa fa-file-excel-o"></i> Excel',
                    titleAttr: 'Export to Excel',
                    className: 'btn btn-success btn-outline btn-rounded',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5]
                    }

                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span>Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'btn btn-danger btn-outline btn-rounded',
                    exportOptions: {
                        columns: [0, 1, 2, 3, 4, 5]
                    }
                },
            ],
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Oev",
                "infoEmpty": "Affichage 0 à 0 de 0 OEV",
                "infoFiltered": "(Filtré de _MAX_ OEV totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ OEV",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });

        $('#Except_doss').on('click', function () {
            if (document.getElementById('Except_doss').checked) {
                document.getElementById("div_motif").style.display = "block";
            } else {
                document.getElementById('Motif').value = '';
                document.getElementById("div_motif").style.display = "none";
            }

        });
        $('#Except_oev').on('click', function () {
            if (document.getElementById('Except_oev').checked) {
                document.getElementById("div_motifoev").style.display = "block";
            } else {
                document.getElementById('Motifoev').value = '';
                document.getElementById("div_motifoev").style.display = "none";
            }

        });

        $('#adddoss').on('click', function () { 
            
            if (document.getElementById('Except_doss').checked && document.getElementById('Motif').value == '')
                alert("Veuillez saisir le motif de la participation");
            else {
                var Ref_doss = document.getElementById('Ref_doss').value;
                if (Ref_doss !== '') {
                    var Comm = <?php echo "'" . $comm['Nume'] . "'"; ?>;
                    var Acti = <?php echo json_encode($comm['Acti']); ?>;
                    var Motif = document.getElementById('Motif').value;
                    var Dat_ = <?php echo json_encode($comm['Dat_']); ?>;
                    var Except_doss = document.getElementById('Except_doss').checked;
                    $.ajax({
                        type: 'POST',
                        url: '<?php echo $this->url('communaute', array('action' => 'Ajax')); ?>',
                        dataType: 'json',
                        data: {'Nume': Ref_doss, 'Comm': Comm, 'Acti': Acti, 'Dat_': Dat_, 'Commp': tabp, 'Except_doss': Except_doss, 'Motif': Motif},
                        success: function (data) {
                            if (data.Nume > 0)
                            {
                                var t = Array();
                                t['1'] = 'Masculin';
                                t['2'] = 'Feminin';
                                var sexe = '';
                                if (data.Sexe) {
                                    sexe = t[data.Sexe];
                                }
                                commdossdatatable.row.add([
                                    data.Ref_,
                                    data.Age_,
                                    sexe,
                                    data.Motif,
                                    '<a title="Supprimer" class="btn btn-sm btn-danger" href="#" id=' + data.Nume + '><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>'
                                ]).draw(false);
                                document.getElementById('Except_doss').checked = false;
                                document.getElementById("div_motif").style.display = "none";
                                document.getElementById('Motif').value = '';
                            } else
                            if (data.Nume === -1)
                            {
                                alert("Le patient a déjà participé à une activité semblable le " + data.Modi);
                            } else {
                                document.getElementById('Except_doss').checked = false;
                                document.getElementById("div_motif").style.display = "none";
                                document.getElementById('Motif').value = '';
                            }
                        },
                        error: function (data) {
                            alert('Une erreur s\'est produite.');
                            console.log(data);
                        }
                    });
                } else {
                    alert("saisir numéro de dossier");
                }
            }
        });
        var nEditing = null;
        $('#addoev').on('click', function (e) {
            if (document.getElementById('Except_oev').checked && document.getElementById('Motifoev').value === '')
                alert("Veuillez saisir le motif de la participation");
            else {
                e.preventDefault();
                var Ref_oev = document.getElementById('Ref_oev').value;
                if (Ref_oev !== '') {
                    var Comm = <?php echo "'" . $comm['Nume'] . "'"; ?>;
                    var Acti = <?php echo json_encode($comm['Acti']); ?>;
                    var Motifoev = document.getElementById('Motifoev').value;
                    var Dat_ = <?php echo json_encode($comm['Dat_']); ?>;
                    console.log('Nume:'+Ref_oev+' Comm:'+ Comm+'Acti:'+ Acti+'Dat_:'+Dat_+'Commp:'+tabp+'Motif:'+ Motifoev);
                    $.ajax({
                        type: 'POST',
                        url: '<?php echo $this->url('communaute', array('action' => 'Ajax2')); ?>',
                        dataType: 'json',
                        data: {'Nume': Ref_oev, 'Comm': Comm, 'Acti': Acti, 'Dat_': Dat_, 'Commp': tabp, 'Motif': Motifoev},
                        success: function (data) {
                            if (data.Nume > 0)
                            {
                                var t = Array();
                                t['1'] = 'Masculin';
                                t['2'] = 'Feminin';
                                var sexe = '';
                                if (data.Sexe) {
                                    sexe = t[data.Sexe];
                                }
                                var aiNew = commoevdatatable.fnAddData([
                                    data.Ref_,
                                    sexe,
                                    data.Age_,
                                    '',
                                    '',
                                    '',
                                    data.Motif,
                                    '<a title="Enregistrer" class="btn btn-sm btn-success" href="#" id=' + data.Nume + '><span class="glyphicon glyphicon-save" aria-hidden="true"></span> </a>' +
                                            ' <a title="Supprimer" class="btn btn-sm btn-danger" href="#" id=' + data.Nume + '> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>'
                                ]
                                        );
                                var nRow = commoevdatatable.fnGetNodes(aiNew[0]);
                                editRow(commoevdatatable, nRow);
                                nEditing = nRow;

                             
                            }
                            if (data.Nume === -1)
                            {
                                alert("Le patient a déjà participé à une activité semblable le " + data.Modi);
                            }
                        },
                        error: function (data) {
                            alert('Dossier OEV non trouvé.');
                            console.log(data);
                        }
                    });
                } else {
                    alert("saisir numéro de oev");
                }
            }
        });

        $('#commdossdatatable tbody').on('click', '.btn.btn-sm.btn-danger', function () {
            var tr = $(this).closest('tr');

            var id = this.id;
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->url('communaute', array('action' => 'delcommdoss')); ?>',
                dataType: 'json',
                data: {'Nume': id, },
                success: function () {
                    commdossdatatable.row(tr).remove().draw();
                },
                error: function () {
                    alert('Erreur Server2');
                }
            });
        });

        $('#commoevdatatable tbody').on('click', '.btn.btn-sm.btn-danger', function () {
            var id = this.id;
            var nRow = $(this).parents('tr')[0];
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->url('communaute', array('action' => 'delcommdoss')); ?>',
                dataType: 'json',
                data: {'Nume': id, },
                success: function () {
                    // commoevdatatable.row(tr).remove().draw();
                    commoevdatatable.fnDeleteRow(nRow);
                },
                error: function () {
                    alert('Erreur Server2');
                }
            });
        });
        $('#commoevdatatable tbody').on('click', '.btn.btn-sm.btn-success', function () {
            var id = this.id;
            var nRow = $(this).parents('tr')[0];
            var aData = commoevdatatable.fnGetData(nRow);
            var jqInputs = $('input', nRow);
            /****/
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->url('communaute', array('action' => 'Ajax2')); ?>',
                dataType: 'json',
                data: {'id': id, 'Tuteur': jqInputs[0].value, 'Montant': jqInputs[1].value},
                success: function (data) {

                },
                error: function () {
                    alert('Erreur interne');
                }
            });
            /****/



            var nRow = $(this).parents('tr')[0];
            saveRow(commoevdatatable, nRow);
        });
        $('#commoevdatatable tbody').on('click', '.btn.btn-sm.btn-primary', function () {
            var nRow = $(this).parents('tr')[0];
            editRow(commoevdatatable, nRow);
        });

        function conversion(socicons)
        {
            var tab = Array();
            for (var i = 0; i < socicons.length; i++)
            {
                for (var indice in socicons[i])
                {
                    if (indice === 'Nume')
                    {
                        tab.push(socicons[i][indice]);
                    }

                }
            }
            return(tab);
        }
        function editRow(oTable, nRow)
        {
            var aData = oTable.fnGetData(nRow);
            var jqTds = $('>td', nRow);
            jqTds[3].innerHTML = '<input type="text" value="' + aData[3] + '">';
            jqTds[4].innerHTML = '<input type="text" value="' + aData[4] + '">';


        }
        function saveRow(oTable, nRow)
        {
            var jqInputs = $('input', nRow);
            console.log(jqInputs);
            var jqa = $('a', nRow);
            oTable.fnUpdate(jqInputs[0].value, nRow, 3, false);
            oTable.fnUpdate(jqInputs[1].value, nRow, 4, false);
          // oTable.fnUpdate(jqInputs[1].value, nRow, 7, false);
            oTable.fnUpdate(' <a title="Supprimer" class="btn btn-sm btn-danger" href="#" id=' + jqa[0].id + '> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>', nRow, 7, false);
            oTable.fnDraw();
            
        }
    });
</script>

