<?php
$title = 'Dispensation';
$this->headTitle($title);
$this->headLink()
        ->prependStylesheet($this->basePath('bootstrap-select.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->appendFile($this->basePath('bootstrap-select.min.js'));
?>
<style>
    div.dataTables_length{
position:relative;
float:left;
}
.space{
    margin-right:10px;
}
</style>

<!-- row -->
<?php
echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left">
                    <?php echo $this->escapeHtml($title); ?>
                </h3>
				<?php  if ($this->IsAllowed()->isAllowed('Dispensation\Controller\Dispensation', 'historique')) { ?>
				<div class="btn-group pull-right">
                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('dispensation', array('action' => 'historique')); ?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Historique de délivrance
                    </a>&nbsp;
                </div>
                <?php } ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <?php echo $this->dataTable('dispdatatable')->renderHtml(); ?>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        $('#dispdb').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                dataType: 'json',
                url: '<?php echo $this->url('dispensation', array('action' => 'data')); ?>',
            },
            deferRender: true,
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            
            "responsive": true,
            language: {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ dossiers",
                "infoEmpty": "Affichage 0 à 0 de 0 dossiers",
                "infoFiltered": "(Filtré de _MAX_ dossiers totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Dossiers",
                "loadingRecords": "<div id='loader'></div>",
                "processing": "<div id='loader'></div>",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
    });
</script>