<?php
$title = 'Pharmacie';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('pharmacie', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/sweet-alert.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-select-master/docs/docs/dist/css/bootstrap-select.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'));
$this->inlineScript()
		->appendFile($this->basePath('themes/datas/assets/sweetalert-master/dist/sweetalert-dev.js'))
        ->appendFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->appendFile($this->basePath('themes/datas/assets/bootstrap-select-master/docs/docs/dist/js/bootstrap-select.min.js'))
        ->appendFile($this->basePath('themes/datas/assets/bootstrap-select-master/js/i18n/defaults-fr_FR.js'));
?>
<div id="page-content-wrapper">
    <?php echo $this->form()->openTag($form); ?>
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Saisir une entrée
			<a href="<?php echo $this->url('pharmacie'); ?>" class="btn btn-warning btn-outline btn-rounded pull-right">Fermer</a>
			</h4>
			</div>
            <div class="modal-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#entree" data-toggle="tab" id="saisirentree">Saisir une entrée</a></li>
                    <li><a href="#produit" data-toggle="tab" id="gestionprod">Gestion de produit</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="entree">
                        <br />
                        <?php
                        echo $this->formHidden($form->get('Nume'));
                        ?>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('ProdForm')->get('Afftype')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formSelect($form->get('ProdForm')->get('Afftype'));
                                        echo $this->formElementErrors($form->get('ProdForm')->get('Afftype'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Prod')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formSelect($form->get('Prod'));
                                        echo $this->formElementErrors($form->get('Prod'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Lot_')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formInput($form->get('Lot_'));
                                        echo $this->formElementErrors($form->get('Lot_'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Expi')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formInput($form->get('Expi'));
                                        echo $this->formElementErrors($form->get('Expi'));
                                        ?>
                                    </div>
                                    
                                  <!--  <label class="control-label col-sm-3">
                                        <?php //echo $this->formLabel($form->get('Expi_moi')); ?>
                                    </label>
                                    <div class="col-sm-5">
                                        <?php
                                      //  echo $this->formSelect($form->get('Expi_moi'));
                                       // echo $this->formElementErrors($form->get('Expi_moi'));
                                        ?>
                                    </div>
                                    <div class="col-sm-4">
                                        <?php
                                       // echo $this->formSelect($form->get('Expi_annee'));
                                       // echo $this->formElementErrors($form->get('Expi_annee'));
                                        ?>
                                    </div>-->
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('NombBoit')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formInput($form->get('NombBoit'));
                                        echo $this->formElementErrors($form->get('NombBoit'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Prov')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formSelect($form->get('Prov'));
                                        echo $this->formElementErrors($form->get('Prov'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Fabr')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formSelect($form->get('Fabr'));
                                        echo $this->formElementErrors($form->get('Fabr'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Chrg')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formSelect($form->get('Chrg'));
                                        echo $this->formElementErrors($form->get('Chrg'));
                                        ?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-sm-3">
                                        <?php echo $this->formLabel($form->get('Dat_')); ?>
                                    </label>
                                    <div class="col-sm-9">
                                        <?php
                                        echo $this->formInput($form->get('Dat_'));
                                        echo $this->formElementErrors($form->get('Dat_'));
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="produit">
                        <br />
                        <ul class="examples col-md-12">
                            <li class="message">
                                <button type="button" class="btn btn-inverse" id="Nonenombre" style="display : none">Click Here!</button>
                            </li>
                        </ul>
                        <div class="row">
                            <div class="col-sm-12"> 
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-prod">
                                        <thead>
                                            <tr>
                                                <th><b>Produit</b></th>
                                                <th><b>Data</b></th>
                                                <th><b>Enstock</b></th>
                                                <th><b></b></th>
                                            </tr>
                                        </thead>
                                        <tbody id="prodtable">
                                            <?php
                                            $i = 0;
                                            if ($medicament)
                                                foreach ($medicament as $medoc) :
                                                    ?>
                                                    <tr id="<?php echo $i; ?>">

                                                        <td><?php echo $this->escapeHtml($medoc['Produit']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['data']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['enstock']); ?></td>
                                                        <td>
                                                            <a data-toggle="modal"  title="Modifier" class="mod btn btn-sm btn-primary" href="#" id="<?php echo $medoc['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                            </a>
                                                            <a data-toggle="modal" title="Supprimer" class="btn btn-sm btn-danger" href="#" id="<?php echo $medoc['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                            </a>
                                                        </td>

                                                    </tr> 
                                                    <?php
                                                    $i++;
                                                endforeach;
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>   

            <div class="modal-footer">
                <div id="mainbtngrp">
                    <button type="submit" name="submit" id="submit" class="btn btn-primary">Valider</button>
                    <span>
                        <button type="reset" name="rest" value="Annuler" class="btn btn-default" aria-label="Close">Annuler</button>
                    </span>
                </div>
                <div id="secbtngrp" style="display : none">
                    <button type="button" class="btn btn-primary" data-toggle="modal" href="#modalform">Ajouter produit</button>
                </div>
            </div>
        </div>
    </div>
    <div id="modalform" class="modal fade" tabindex="-1"  aria-labelledby="" aria-hidden="true" >
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Gestion produit</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label col-sm-3">
                                    <?php echo $this->formLabel($form->get('ProdForm')->get('Dci_')); ?>
                                </label>
                                <div class="col-sm-9">
                                    <?php
                                    echo $this->formSelect($form->get('ProdForm')->get('Dci_'));
                                    echo $this->formElementErrors($form->get('ProdForm')->get('Dci_'));
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">
                                    <?php echo $this->formLabel($form->get('ProdForm')->get('Dosa')); ?>
                                </label>
                                <div class="col-sm-9">
                                    <?php
                                    echo $this->formSelect($form->get('ProdForm')->get('Dosa'));
                                    echo $this->formElementErrors($form->get('ProdForm')->get('Dosa'));
                                    ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label class="control-label col-sm-3">
                                    <?php echo $this->formLabel($form->get('ProdForm')->get('Gale')); ?>
                                </label>
                                <div class="col-sm-9">
                                    <?php
                                    echo $this->formSelect($form->get('ProdForm')->get('Gale'));
                                    echo $this->formElementErrors($form->get('ProdForm')->get('Gale'));
                                    ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-3">
                                    <?php echo $this->formLabel($form->get('ProdForm')->get('Cont')); ?>
                                </label>
                                <div class="col-sm-5">
                                    <?php
                                    echo $this->formInput($form->get('ProdForm')->get('Cont'));
                                    echo $this->formElementErrors($form->get('ProdForm')->get('Cont'));
                                    ?>
                                </div>
                                <div class="col-sm-4">
                                    <?php
                                    echo $this->formSelect($form->get('ProdForm')->get('Unit'));
                                    echo $this->formElementErrors($form->get('ProdForm')->get('Unit'));
                                    ?>
                                </div>
                            </div>
                        </div
                    </div>                   
                </div>
                <div class="modal-footer">
                    <button name="validprod" type="button" class="btn btn-primary" id="validprod">Ajouter</button>
                    <span>
                        <button type="reset" name="rest" value="Annuler" class="btn btn-default" aria-label="Close" id="reset">Annuler</button>
                    </span>
                </div>  
            </div>
        </div>   

    </div>     
</div>
</div>


<?php echo $this->form()->closeTag() ?>

<script>

    $(document).ready(function () {
        var Nume = null;
        var rowindex = null;
        var tr = null;
        var donnee;
        var errmsg;
        document.querySelector('ul.examples li.message button').onclick = function () {
            swal(errmsg);
        };
        var prodtable = $('#dataTables-prod').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ medicaments",
                "infoEmpty": "Affichage 0 à 0 de 0 medicaments",
                "infoFiltered": "(Filtré de _MAX_ medicaments totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ medicaments",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Rechercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            },
            "columnDefs": [
                {
                    "targets": [1],
                    "visible": false,
                    "searchable": false
                },
                {
                    "targets": [2],
                    "visible": false,
                    "searchable": false
                },
            ],
            "bLengthChange": false,
            "info": false,
            "ordering": false,
            "iDisplayLength": 10,
            "aLengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]]
        });
        $('#dataTables-prod tbody').on('click', '.mod.btn.btn-sm.btn-primary', function () {
            tr = this.closest('tr');
            var donnee = prodtable.row(tr).data();
            if (donnee[2] == "NOK") {
                document.getElementById("validprod").innerHTML = "Modifier";
                rowindex = this.closest('tr').id;
                donnee = donnee[1].split('$');
                $('#Dci_').val(donnee[0]);
                $('#Dosa').val(donnee[1]);
                $('#Gale').val(donnee[2]);
                $('#Cont').val("");
                if (donnee[3] !== '0' && donnee[3] !== '')
                {
                    $('#Cont').val(donnee[3]);
                    $('#Unit').val(donnee[4]);
                }
                Nume = this.id;
                refrechselect();
                $('#modalform').modal('show');
            }
            else
            {
                errmsg = "Produit est déjà en stock il ne peut être modifié";
                $('#Nonenombre').click();
            }
        });
        $('#dataTables-prod tbody').on('click', '.btn.btn-sm.btn-danger', function () {

            var tr = this.closest('tr');
            var donnee = prodtable.row(tr).data();
            if (donnee[2] == "NOK") {
                var id = this.id;
                donnee = prodtable.row(tr).remove();
                $.ajax({
                    type: 'POST',
                    url: '<?php echo $this->url('pharmacie', array('action' => 'delprod')); ?>',
                    dataType: 'json',
                    data: {'Nume': id},
                    success: function () {
                        tr.remove();
                        $("#Prod option[value='" + id + "']").remove();
                        $('#Prod').selectpicker("refresh");
                    },
                    error: function () {
                        alert('Erreur Server2');
                    }
                });
            }
            else {
                errmsg = "Produit est déjà en stock il ne peut être supprimé";
                $('#Nonenombre').click();
            }
        });
        $('#validprod').on('click', function () {
            var Cont = $('#Cont').val();
            if ($('#Cont').val() === "")
            {
                Cont = 0;
            }
            var Dci_ = $('#Dci_').val();
            var Dci_Desi = $('#Dci_ option:selected').text();
            var Dosa = $('#Dosa').val();
            var DosaDesi = $('#Dosa option:selected').text();
            var Gale = $('#Gale').val();
            var GaleDesi = $('#Gale option:selected').text();
            var Typ_ = $('#Afftype').val();
            var Unit = $('#Unit').val();
            console.log('Nume='+Nume+'Cont='+Cont+'Dci_='+Dci_+'Dci_Desi='+Dci_Desi+'Dosa='+Dosa+'DosaDesi='+DosaDesi+'Gale='+Gale+'GaleDesi='+GaleDesi+'Typ_='+Typ_+'Unit='+Unit);
            
            $.ajax({
                type: 'POST',
                url: '<?php echo $this->url('pharmacie', array('action' => 'Ajax')); ?>',
                dataType: 'json',
                data: {'Nume': Nume, 'Cont': Cont, 'Dci_': Dci_, 'Dci_Desi': Dci_Desi, 'Dosa': Dosa, 'DosaDesi': DosaDesi, 'Gale': Gale, 'GaleDesi': GaleDesi, 'Typ_': Typ_, 'Unit': Unit},
                success: function (data) {
                    var donnee = Array();
                    if (!data.Typ_ && !data.Nume) {
                        errmsg = "Ce produit existe déjà dans la liste";
                        $('#Nonenombre').click();
                    }
                    else {
                        donnee[0] = data.Dci_Desi + " " + data.DosaDesi + " " + data.GaleDesi;
                        donnee[1] = data.Dci_ + "$" + data.Dosa + "$" + data.Gale + "$" + data.Cont + "$" + data.Unit;
                        donnee[2] = 'NOK';
                        donnee[3] = '<a data-toggle="modal" title="Modifier" class="mod btn btn-sm btn-primary" href="#" id="' + data.Nume + '"> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a> <a data-toggle="modal" title="Supprimer" class="btn btn-sm btn-danger" href="#" id="' + data.Nume + '"> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>'
                        if (data.Cont !== '0')
                        {
                            donnee[0] += " (" + data.Cont + data.Unit + " )";
                        }
                        if (Nume)//modif
                        {
                            prodtable.row(tr).data(donnee).draw(false);
                            $('#Prod').val(data.Nume);
                            $('#Prod option:selected').text(donnee[0]);
                        }
                        else {
                            prodtable.row.add([
                                donnee[0],
                                donnee[1],
                                donnee[2],
                                donnee[3]
                            ]).draw(false);
                            $('#Prod').append($('<option>', {
                                value: data.Nume,
                                text: donnee[0]
                            }));
                            $('#Prod').val(data.Nume);
                        }
                        
                        $('#Prod').selectpicker("refresh");
                        $('#Dci_').val("");
                        $('#Dosa').val("");
                        $('#Gale').val("");
                        $('#Gale').val("");
                        $('#Cont').val("");
                        $('#Unit').val("");
                        refrechselect();
                        $('#modalform').modal('hide');
                        document.getElementById("validprod").innerHTML = "Ajouter";
                        Nume = null;
                    }
                },
                error: function (data) {
                    alert('Erreur Server' + data);
                }
            });
        });
        $('#modalform').on('hidden.bs.modal', function () {
            Nume = null;
            $(this).find("input,textarea,select").val('').end();
            refrechselect();           
            document.getElementById("validprod").innerHTML = "Ajouter";
        });
        $('#saisirentree').on('click', function () {
            document.getElementById('mainbtngrp').style = "display : block";
            document.getElementById('secbtngrp').style = "display : none";
        });
        $('#gestionprod').on('click', function () {
            document.getElementById('mainbtngrp').style = "display : none";
            document.getElementById('secbtngrp').style = "display : block";
        });
        $('#reset').on('click', function () {
            refreshselect();
        });
        function refrechselect(){
                $('#Dci_').selectpicker("refresh");
                $('#Dosa').selectpicker("refresh");
                $('#Gale').selectpicker("refresh");
                $('#Unit').selectpicker("refresh");
        }
    });
</script>