<?php
$title = 'Supprimez un dossier';
$this->headTitle($title);
$url = $this->url('pharmacie', array(
    'action' => 'delete',
    'Nume' => $this->Nume,
        ));
?>


<div class="modal-header">
    <h3 class="panel-title">
        <?php echo $this->escapeHtml($title); ?>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </h3>
</div>
<div class="modal-body">
    <p>Etes-vous sûr que vous voulez supprimer</p>
</div>
<div class="modal-footer">
    <form action="<?php echo $url; ?>" method="post">
        <input type="hidden" name="Nume" value="<?php echo  $this->Nume; ?>" />
        <button type="submit" name="del" value="Oui" class="btn btn-danger" ><span aria-hidden="true">Oui</span></button>
        <span>
            <button type="submit" name="del" value="Non" class="btn btn-default">Non</button>
        </span>
    </form>        
</div>


