<?php
$title = 'Pharmacie';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('pharmacie', array('action' => 'index', 'Nume' => $this->Nume,)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('bootstrap-select.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/sweet-alert.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
		->appendFile($this->basePath('themes/datas/assets/sweetalert-master/dist/sweetalert-dev.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->appendFile($this->basePath('bootstrap-select.min.js'));
	
?>
<style>
    div.dataTables_length{
position:relative;
float:left;
}
.space{
    margin-right:10px;
}
</style>
<!-- Page Level JS -->
<!-- row -->
<?php
echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#Medicaments" data-toggle="tab">Medicaments</a></li>
                    <li><a href="#Arv" data-toggle="tab">Arv</a></li>
                    <li><a href="#Consommables" data-toggle="tab">Consommables</a></li>
                    <li><a href="#Laboratoire" data-toggle="tab">Laboratoire</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="Medicaments">
                        <div class="panel panel-primary-border-top">
                            <div class="panel-heading clearfix">
                                <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                <div class="btn-group pull-right">
                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '1')); ?>" id="saisientrmedi" style="display:block">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                    </a>
                                </div>
                                <?php } ?>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-meditable">
                                        <thead>
                                            <tr>
                                                <th><b>Désignation</b></th>
                                                <th><b>Dosage</b></th>
                                                <th><b>Forme</b></th>
                                                <th><b>Fabricant</b></th>
                                                <th><b>N° de Lot</b></th>
                                                <th><b>Date de Péremption</b></th>
                                                <th><b>Nbr d'unités</b></th>
                                                <th><b>Provenances</b></th>
                                                <th><b>Prise en Charge</b></th>
                                                <th><b>Action</b></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $i = 0;
                                            if ($medicament)
                                                foreach ($medicament as $medoc) :
                                                    ?>
                                                    <tr id="<?php echo $i; ?>">
                                                        <td><?php echo $this->escapeHtml($medoc['Desi']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['Dosa']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['Gale']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['Fabr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['Lot']); ?></td>
                                                        <td>

                                                            <?php
                                                            if ($medoc['etat'] === 'perime')
                                                                echo "<span class='label label-danger'>" . $this->escapeHtml($medoc['peremption']) . "</span>";
                                                            else
                                                                echo $this->escapeHtml($medoc['peremption']);
                                                            ?>
                                                        </td>
                                                        <td><?php echo $this->escapeHtml($medoc['Nbr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['Prov']); ?></td>
                                                        <td><?php echo $this->escapeHtml($medoc['Chrg']); ?></td>
                                                        <td>
                                                            <a data-toggle="modal" title="Sortie" class="sortie btn btn-sm btn-primary btn-outline btn-rounded" href="#sortiemodalform" id="<?php echo $medoc['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                                                            </a>
                                                        </td>
                                                    </tr> 
                                                    <?php
                                                    $i++;
                                                endforeach;
                                            ?>
                                        </tbody>
                                    </table>
                                </div> 
                                <!--pour le nom du medoc s'affiche sur le modal de sortie-->                    
                                <input name="sortietitle" type="hidden" id="sortietitle" value="">
                                <input name="nbstock" type="hidden" id="nbstock" value="">
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class='col-sm-12'>
                                        <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                        <div class="btn-group pull-right">
                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '1')); ?>" id="saisientrmedi" style="display:block">
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                            </a>
                                        </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="Arv">
                        <div class="panel panel-success-border-top">
                            <div class="panel-heading clearfix">
                                <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                <div class="btn-group pull-right">
                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '3')); ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                    </a>
                                </div>
                                <?php } ?>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">                        
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-arvtable">
                                        <thead>
                                            <tr>
                                                <th><b>Designation</b></th>
                                                <th><b>Dosage</b></th>
                                                <th><b>Forme</b></th>
                                                <th><b>Fabricant</b></th>
                                                <th><b>N° de Lot</b></th>
                                                <th><b>Péremption</b></th>
                                                <th><b>Nbr d'unités</b></th>
                                                <th><b>Provenances</b></th>
                                                <th><b>Prise en Charge</b></th>
                                                <th><b></b></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $i = 0;
                                            if ($arv)
                                                foreach ($arv as $arvs) :
                                                    ?>
                                                    <tr id="<?php echo $i; ?>">
                                                        <td><?php echo $this->escapeHtml($arvs['Desi']); ?></td>
                                                        <td><?php echo $this->escapeHtml($arvs['Dosa']); ?></td>
                                                        <td><?php echo $this->escapeHtml($arvs['Gale']); ?></td>
                                                        <td><?php echo $this->escapeHtml($arvs['Fabr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($arvs['Lot']); ?></td>

                                                        <td><?php
                                                            if ($arvs['etat'] === 'perime') {
                                                                echo "<span class='label label-danger'>" . $this->escapeHtml($arvs['peremption']) . "</span>";
                                                            } else {
                                                                echo $this->escapeHtml($arvs['peremption']);
                                                                //echo $this->escapeHtml($arvs['etat']); 
                                                            }
                                                            ?>
                                                        </td>
                                                        <td><?php echo $this->escapeHtml($arvs['Nbr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($arvs['Prov']); ?></td>
                                                        <td><?php echo $this->escapeHtml($arvs['Chrg']); ?></td>
                                                        <td>
                                                            <a data-toggle="modal" title="Sortie" class="sortie btn btn-sm btn-primary btn-outline btn-rounded" href="#sortiemodalform" id="<?php echo $arvs['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                                                            </a>
                                                        </td>
                                                    </tr> 
                                                    <?php
                                                    $i++;
                                                endforeach;
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class='col-sm-12'>
                                        <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                        <div class="btn-group pull-right">
                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '3')); ?>">
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                            </a>
                                        </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="Consommables">
                        <div class="panel panel-warning-border-top">
                            <div class="panel-heading clearfix">
                                <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                <div class="btn-group pull-right">
                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '2')); ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                    </a>
                                </div>
                                <?php } ?>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">                        
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-constable">
                                        <thead>
                                            <tr>
                                                <th><b>Designation</b></th>
                                                <th><b>Dosage</b></th>
                                                <th><b>Forme</b></th>
                                                <th><b>Fabricant</b></th>
                                                <th><b>N° de Lot</b></th>
                                                <th><b>Péremption</b></th>
                                                <th><b>Nbr d'unités</b></th>
                                                <th><b>Provenances</b></th>
                                                <th><b>Prise en Charge</b></th>
                                                <th><b></b></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $i = 0;
                                            if ($consommable)
                                                foreach ($consommable as $cons) :
                                                    ?>
                                                    <tr id="<?php echo $i; ?>">

                                                        <td><?php echo $this->escapeHtml($cons['Desi']); ?></td>
                                                        <td><?php echo $this->escapeHtml($cons['Dosa']); ?></td>
                                                        <td><?php echo $this->escapeHtml($cons['Gale']); ?></td>
                                                        <td><?php echo $this->escapeHtml($cons['Fabr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($cons['Lot']); ?></td>
                                                        <td>
                                                            <?php
                                                            if ($cons['etat'] === 'perime')
                                                                echo "<span class='label label-danger'>" . $this->escapeHtml($cons['peremption']) . "</span>";
                                                            else
                                                                echo $this->escapeHtml($cons['peremption']);
                                                            ?>
                                                        </td>
                                                        <td><?php echo $this->escapeHtml($cons['Nbr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($cons['Prov']); ?></td>
                                                        <td><?php echo $this->escapeHtml($cons['Chrg']); ?></td>
                                                        <td>
                                                            <a data-toggle="modal" title="Sortie" class="sortie btn btn-sm btn-primary btn-outline btn-rounded" href="#sortiemodalform" id="<?php echo $cons['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                                                            </a>
                                                        </td>

                                                    </tr> 
                                                    <?php
                                                    $i++;
                                                endforeach;
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class='col-sm-12'>
                                        <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                        <div class="btn-group pull-right">
                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '2')); ?>">
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                            </a>
                                        </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="Laboratoire">
                        <div class="panel panel-primary-border-top">
                            <div class="panel-heading clearfix">
                                <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                <div class="btn-group pull-right">
                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '4')); ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                    </a>
                                </div>
                                <?php } ?>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">

                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-labotable">
                                        <thead>
                                            <tr>
                                                <th><b>Designation</b></th>
                                                <th><b>Dosage</b></th>
                                                <th><b>Forme</b></th>
                                                <th><b>Fabricant</b></th>
                                                <th><b>N° de Lot</b></th>
                                                <th><b>Péremption</b></th>
                                                <th><b>Nbr d'unités</b></th>
                                                <th><b>Provenances</b></th>
                                                <th><b>Prise en Charge</b></th>
                                                <th><b></b></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $i = 0;
                                            if ($laboratoire)
                                                foreach ($laboratoire as $labo) :
                                                    ?>
                                                    <tr id="<?php echo $i; ?>">

                                                        <td><?php echo $this->escapeHtml($labo['Desi']); ?></td>
                                                        <td><?php echo $this->escapeHtml($labo['Dosa']); ?></td>
                                                        <td><?php echo $this->escapeHtml($labo['Gale']); ?></td>
                                                        <td><?php echo $this->escapeHtml($labo['Fabr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($labo['Lot']); ?></td>
                                                        <td>
                                                            <?php
                                                            if ($labo['etat'] === 'perime')
                                                                echo "<span class='label label-danger'>" . $this->escapeHtml($labo['peremption']) . "</span>";
                                                            else
                                                                echo $this->escapeHtml($labo['peremption']);
                                                            ?>
                                                        </td>

                                                        <td><?php echo $this->escapeHtml($labo['Nbr']); ?></td>
                                                        <td><?php echo $this->escapeHtml($labo['Prov']); ?></td>
                                                        <td><?php echo $this->escapeHtml($labo['Chrg']); ?></td>
                                                        <td>
                                                            <a title="Sortie" class="sortie btn btn-sm btn-primary btn-outline btn-rounded" data-toggle="modal"  href="#sortiemodalform" id="<?php echo $labo['Nume']; ?>">
                                                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                                                            </a>
                                                        </td>

                                                    </tr> 
                                                    <?php
                                                    $i++;
                                                endforeach;
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class='col-sm-12'>
                                        <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'add')) { ?>
                                        <div class="btn-group pull-right">
                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('pharmacie', array('action' => 'add', 'Nume' => '4')); ?>" >
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une entrée
                                            </a>
                                        </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

<div class="modal fade" id="sortiemodalform" tabindex="-1" role="dialog" aria-labelledby="sortiemodalform" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Saisir une sortie</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <ul class="examples col-md-12">
                        <div class="row">
                            <li class="message">
                                <button class="btn btn-inverse" id="Errnombre" style="display : none">Click Here!</button>
                            </li>
                        </div> 
                    </ul>
                </div> 
                <?php echo $this->form()->openTag($form); ?> 
                <?php
                echo $this->formHidden($form->get('Numehidden'));
                ?>
                <div class="bg-primary text-center" id='titreprod'><strong> </strong></div>
                <br>
                <div class="form-group">
                    <label class="control-label col-sm-3">
                        <?php echo $this->formLabel($form->get('NombBoit')); ?>
                    </label>
                    <div class="col-sm-9">
                        <?php
                        echo $this->formInput($form->get('NombBoit'));
                        echo $this->formElementErrors($form->get('NombBoit'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">
                        <?php echo $this->formLabel($form->get('Dest')); ?>
                    </label>
                    <div class="col-sm-9">
                        <?php
                        echo $this->formSelect($form->get('Dest'));
                        echo $this->formElementErrors($form->get('Dest'));
                        ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-3">
                        <?php echo $this->formLabel($form->get('Dat_')); ?>
                    </label>
                    <div class="col-sm-9">
                        <?php
                        echo $this->formInput($form->get('Dat_'));
                        echo $this->formElementErrors($form->get('Dat_'));
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
            <div class="modal-footer">
                <button type="button" name="sortie_button" id="sortie_button" class="btn btn-primary">Valider</button>
                <span>
                    <button type="button" name="rest" value="Annuler" class="btn btn-default" data-dismiss="modal" aria-label="Close">Annuler</button>
                </span>
            </div>
        </div>
    </div>
</div>



<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        var meditable = $('#dataTables-meditable').DataTable({
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ medicaments",
                "infoEmpty": "Affichage 0 à 0 de 0 medicaments",
                "infoFiltered": "(Filtré de _MAX_ medicaments totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ medicaments",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        var arvtable = $('#dataTables-arvtable').DataTable({
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ ARV",
                "infoEmpty": "Affichage 0 à 0 de 0 ARV",
                "infoFiltered": "(Filtré de _MAX_ ARV totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ ARV",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        var constable = $('#dataTables-constable').DataTable({
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ consommable",
                "infoEmpty": "Affichage 0 à 0 de 0 consommable",
                "infoFiltered": "(Filtré de _MAX_ consommable totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ consommable",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        var labotable = $('#dataTables-labotable').DataTable({
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ laboratoire",
                "infoEmpty": "Affichage 0 à 0 de 0 laboratoire",
                "infoFiltered": "(Filtré de _MAX_ laboratoire totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ laboratoire",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
		function setform(id){
			$('#Nume').val(id);
            $('#NombBoit').val('0');
            $('#Dest').val('');
            $('#Dest').selectpicker("refresh");
		}


        var title = "";
        var nbstock = "";
        $('#dataTables-meditable tbody').on('click', '.sortie', function () {
			setform(this.id);
			tr = this.closest('tr');
            donnee = meditable.row(tr).data();
            title = donnee[0] + " " + donnee[1] + " " + donnee[2];
            document.getElementById("titreprod").innerHTML = '<strong><h4>' + title + '</h4></strong>';
            nbstock = donnee[6];
        });
        $('#dataTables-arvtable tbody').on('click', '.sortie', function () {
			setform(this.id);
            tr = this.closest('tr');
            donnee = arvtable.row(tr).data();
            title = donnee[0] + " " + donnee[1] + " " + donnee[2];
            document.getElementById("titreprod").innerHTML = '<strong><h4>' + title + '</h4></strong>';
            nbstock = donnee[6];
        });
        $('#dataTables-constable tbody').on('click', '.sortie', function () {
			setform(this.id);
            tr = this.closest('tr');
            donnee = constable.row(tr).data();
            title = donnee[0] + " " + donnee[1] + " " + donnee[2];
            document.getElementById("titreprod").innerHTML = '<strong><h4>' + title + '</h4></strong>';
            nbstock = donnee[6];
        });
        $('#dataTables-labotable tbody').on('click', '.sortie', function () {
			setform(this.id);
            tr = this.closest('tr');
            donnee = labotable.row(tr).data();
            title = donnee[0] + " " + donnee[1] + " " + donnee[2];
            document.getElementById("titreprod").innerHTML = '<strong><h4>' + title + '</h4></strong>';
            nbstock = donnee[6];
        });

        var errtitle = "";
        nbstock = parseInt(nbstock);
        document.querySelector('ul.examples li.message button').onclick = function () {
            swal(errtitle);
        };
        $('#sortie_button').click(function () {
            var nb = $('#NombBoit').val();
            nb = parseInt(nb);
            if (nb < 0) {
                errtitle = "Saisir un nombre positif.";
                $('#Errnombre').click();
            }
            else
            {
                if (nb > nbstock) {
                    errtitle = "Saisir un nombre inférieur ou égal au stock.";
                    $('#Errnombre').click();
                }
                else
                {
					if($('#Dest').val())
                    document.getElementById("sortiestock").submit();
					else
					{
						errtitle = "Saisir une destination";
                    $('#Errnombre').click();
					}
						
                }
            }
        });

    });
</script>