<?php
$title = 'Maj';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('accueil', array('action' => 'majrdv', 'Nume' => $this->Nume,)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('Nume')); ?>
<div class="modal-header">
    <h4 class="modal-title">
        <?php echo $this->escapeHtml($title); ?>
    </h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <label class="control-label col-sm-3">
                    <?php echo $this->formLabel($form->get('Rdv_Horo')); ?>
                </label>
                <div class="col-sm-9">
                    <?php
                    echo $this->formInput($form->get('Rdv_Horo'));
                    echo $this->formElementErrors($form->get('Rdv_Horo'));
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="submit" name="submit" class="btn btn-primary">Valider</button>
    <span>
        <button type="button" name="rest" value="Annuler" class="btn btn-default" data-dismiss="modal" aria-label="Close">Annuler</button>
    </span>
</div>
<?php echo $this->form()->closeTag() ?>
