<?php
$title = 'Rendez-vous';
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'));
?>
<!-- row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
            </div>            
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="rdvtable">
                        <thead>
                            <tr>
                                <th><b>Date de rendez-vous</b></th>
                                <th><b>N° Dossier</b></th>
                                <th><b>Motif</b></th>
                                <th><b>Action</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($Rdvs as $entr) : ?>
                                <tr>
                                    <td><?php echo $this->escapeHtml($entr->Rdv_Horo); ?></td>
                                    <td><?php echo $this->escapeHtml($entr->Doss); ?></td>
                                    <td><?php echo $this->escapeHtml($entr->Moti); ?></td>
                                    <td>
                                        <a data-toggle="modal" data-target="#infos" title="Maj" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'majrdv', 'Nume' => $entr->Nume)); ?>">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Maj
                                        </a>              
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12">
                        <div class='pull-left'>
                            <form method="post" class="form-inline" action="<?php echo $this->url('accueil', array('action' => 'rdvlist')); ?>">
                                <div class="form-group">
                                    De : 
                                    <span class="input-group date">
                                        <input type='date' class="form-control" name="daymin" id="daymin" value="<?php echo $daymin; ?>" />
                                    </span>
                                    à : <span class="input-group date">
                                        <input type='date' class="form-control" name="daymax" id="daymax" value="<?php echo $daymax; ?>"/>
                                    </span>
                                    <span class="input-group">
                                        <input type="submit" class="btn btn-sm btn-primary btn-outline btn-rounded" value="Filtre">
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#rdvtable').DataTable({
            dom: 'Blfrtip',
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ RDV",
                "infoEmpty": "Affichage 0 à 0 de 0 RDV",
                "infoFiltered": "(Filtré de _MAX_ RDV totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ RDV",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "<b>Rechercher:</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
    });

</script>