<?php
$title = 'Supprimez une arrivée';
$this->headTitle($title);
$url = $this->url('accueil', array(
    'action' => 'delete',
    'Nume' => $this->Nume,
        ));
?>

<form action="<?php echo $url; ?>" method="post">
    <div class="modal-header">
        <h3 class="panel-title">
            <?php echo $this->escapeHtml($title); ?>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </h3>
    </div>
    <div class="modal-body">
        <p><center><h4>Voulez-vous vraiment supprimer l'arrivée ?</h4></center></p>
        <input type="hidden" name="Nume" value="<?php echo  $entr->Nume; ?>" />
    </div>
    <div class="modal-footer">
        <button type="submit" name="del" value="Non"  class="btn btn-default btn-outline btn-rounded">Non</button>
        <span>
            <button type="submit" name="del" value="Oui"  class="btn btn-danger btn-outline btn-rounded">Oui</button>
        </span>
    </div>
</form>        

