<?php
$title = 'Accueil';
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'));
?>
<!-- row -->
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <div class="btn-group pull-right">
                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'add')); ?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une arrivée
                    </a>&nbsp;
                </div>
                <div class="btn-group pull-right">
                    <a title="Planning" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'Planning')); ?>">
                        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Planning
                    </a>&nbsp;
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive " >
                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Arrivée</th>
                                <th>RDV</th>
                                <th>N° dossier</th>
                                <th>Autre N°</th>
                                <th>Patient</th>
                                <th>Age</th>
                                <th>Motif</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($entrs as $entr) : ?>
                                <tr>
                                    <td>
                                        <?php if ($entr->Arri == 0) { ?>
                                            <a title="Arrivée" class="btn btn-sm btn-primary" href="<?php echo $this->url('accueil', array('action' => 'rdv', 'Nume' => $entr->Nume)); ?>">
                                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                            </a>
                                            <?php
                                        } else {
                                            echo $this->escapeHtml($entr->ArriHoro);
                                        }
                                        ?>
                                    </td>
                                    <td><?php if (!is_object($entr->Rdv_Horo)) echo $this->escapeHtml($entr->Rdv_Horo); ?></td>
                                    <td><?php if (!is_object($entr->Cta_Nume)) echo $this->escapeHtml($entr->Cta_Nume); ?></td>
                                    <td><?php if (!is_object($entr->ExteNume)) echo $this->escapeHtml($entr->ExteNume); ?></td>
                                    <td><?php if (!is_object($entr->Sexe) && !is_object($entr->Nom_) && !is_object($entr->Pnom)) echo $this->escapeHtml($entr->Sexe . ' ' . $entr->Nom_ . ', ' . $entr->Pnom); ?></td>
                                    <td><?php if (!is_object($entr->Age_)) echo $this->escapeHtml($entr->Age_); ?></td>
                                    <?php $a = array("default"=>"default","primary"=>"primary","danger"=>"danger","success"=>"success","info"=>"infos"); ?>
                                    <td><span class="label label-<?php echo array_rand($a,1); ?>"><?php if (!is_object($entr->Moti)) echo str_replace("-","<br /></span><span class='label label-".array_rand($a,1)."'>",$entr->Moti); ?></span></td>
                                    <td>
                                        <a title="Modifier" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'edit', 'Nume' => $entr->Nume)); ?>">
                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                        </a>
                                        <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'delete', 'Nume' => $entr->Nume)); ?>">
                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        </a>
                                    </td>
                                </tr> 
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-12">
                        <div class='pull-left'>
                            <form method="post" class="form-inline" action="<?php echo $this->url('accueil'); ?>" id="formday">
                                <div class="form-group">
                                    De : 
                                    <span class="input-group date" id="datetimepicker1">
                                        <input type='date' class="form-control" name="daymin" id="hiddenFieldID1" value="<?php echo $this->escapeHtml($this->daymin); ?>"/>
                                    </span>
                                    à : <span class="input-group date" id="datetimepicker2">
                                        <input type='date' class="form-control" name="daymax" id="hiddenFieldID2" value="<?php echo $this->escapeHtml($this->daymax); ?>"/>
                                    </span>
                                    <span class="input-group">
                                        <input type="submit" class="btn btn-sm btn-primary btn-outline btn-rounded" value="Filtre">
                                    </span>
                                </div>
                            </form>
                        </div>
                        <div class="pull-right">
                            <a  title="Nouveau" class="btn  btn-primary btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'add')); ?>">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Saisir une arrivée
                            </a>&nbsp;
                        </div>
                        <div class="pull-right">
                            <a title="Planning" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('accueil', array('action' => 'Planning')); ?>">
                                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Planning
                            </a>&nbsp;
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.panel -->

    </div>
</div>

<script>
    $(document).ready(function () {
        var table = $('#dataTables-example').DataTable({
            deferRender: true,
            dom: 'Bfrtip',
            buttons : [
                {
                    extend: 'copyHtml5',
                    text: '<span class="glyphicon glyphicon-copy"></span> Copier ',
                    className: 'btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span> Excel ',
                    className: 'btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span> Imprimer ',
                    message: 'Amnir Echiva',
                    className: 'btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            responsive: true,
            language : {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ entrées",
                "infoEmpty": "Affichage 0 à 0 de 0 entrées",
                "infoFiltered": "(Filtré de _MAX_ entrées totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Entrées",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Rehercher:",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
    });
</script>
<script>
    $(document).ready(function () {
        /* initialize the external events */
        $('#external-events .fc-event').each(function () {
            // store data so the calendar knows to render an event upon drop
            $(this).data('event', {
                title: $.trim($(this).text()), // use the element's text as the event title
                stick: true // maintain when user navigates (see docs on the renderEvent method)
            });
            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 999,
                revert: true, // will cause the event to go back to its
                revertDuration: 0  //  original position after the drag
            });
        });
        /* initialize the calendar */
        $('#calendar').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,'
            },
            editable: true,
            droppable: true, // this allows things to be dropped onto the calendar
            drop: function () {
                $(this).remove();
            }
        });
    });
</script>
