<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Amnir Echiva')->setSeparator(' - ')->setAutoEscape(false);

        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <!-- Icon -->
        <link rel="icon" href="themes/datas/images/icon.ico" />
        <?php
        echo $this->headLink()
                ->appendStylesheet($this->basePath('themes/datas/css/csk.css'))
                ->appendStylesheet($this->basePath('themes/datas/css/lite-csk.css'))
                ->appendStylesheet($this->basePath('themes/datas/css/media-query.css'))
                ->prependStylesheet($this->basePath('themes/datas/assets/animate.css-master/animate.min.css'))
                ->prependStylesheet($this->basePath('themes/datas/bootstrap/css/bootstrap.min.css'));

        $this->inlineScript()
                ->prependFile($this->basePath('themes/datas/js/app.js'))
                ->prependFile($this->basePath('themes/datas/assets/jQuery-slimScroll-1.3.8/jquery.slimscroll.js'))
                ->prependFile($this->basePath('themes/datas/assets/metisMenu-master/dist/metisMenu.min.js'))
                ->prependFile($this->basePath('themes/datas/bootstrap/js/bootstrap.min.js'))
                ->prependFile($this->basePath('themes/datas/assets/jquery-1.12.4/jquery-1.12.4.js'));
        ?>

        <style>
            td.highlight {
                background-color: #FFCC66;
            }
        </style>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-fixed-top notification navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="/Echiva2/public" class="navbar-brand">
                        <span class="csk-brand">
                            <img src="themes/datas/images/icon.png" class="img-responsive" alt="AE" title="Amnir Echiva" >
                        </span>
                    </a>
                </div>
                <a href="#menu-toggle" class="" id="menu-toggle"><i class="fa fa-bars" aria-hidden="true"></i></a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <?php
                                $email = $this->zfcUserIdentity()->getEmail();
                                $settings = array('default_img' => \Zend\View\Helper\Gravatar::DEFAULT_MM);
                                $attr = array('class' => 'user-image',);
                                echo $this->gravatar($email, $settings, $attr);
                                ?>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?>
                                    <p>
                                        <?php echo $this->zfcUserDisplayName() ?>
                                        <small><?php echo $this->zfcUserIdentity()->getEmail() ?></small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li>
                                    <a href="<?php echo $this->url('zfcuser/changeemail') ?>"><i class="icon icon-li-envelope sIcon"></i><?php echo $this->translate('Changer l\'e-mail'); ?></a>
                                </li>
                                <li>
                                    <a href="<?php echo $this->url('zfcuser/changepassword') ?>"><i class="icon icon-li-key sIcon"></i><?php echo $this->translate('Changer le mot de passe'); ?></a>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="<?php echo $this->url('zfcuser') ?>" class="btn btn-primary"><?php echo $this->translate('Profil'); ?></a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="<?php echo $this->url('zfcuser/logout') ?>" class="btn btn-danger"><?php echo $this->translate('Déconnexion'); ?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- # navbar-custom-menu -->
            </div>
            <!-- # container-fluid -->
        </nav>
        <!-- Main Body content starts here -->
        <div id="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <aside class="sidebar ">
                    <nav class="sidebar-nav" id="sidebarscroll">
                        <ul class="metismenu ripple" id="menu">
                            <li><br /><br /></li>
                            <li>
                                <a href="<?php echo $this->url('accueil') ?>" title="Accueil" >
                                    <span class="sidebar-nav-item-icon icon-li-home fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Accueil</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('depistage') ?>" title="Depistage">
                                    <span class="sidebar-nav-item-icon icon-li-eye fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Depistage</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('laboratoire') ?>" title="Laboratoire" >
                                    <span class="sidebar-nav-item-icon icon-li-video fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Laboratoire</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('pharmacie') ?>" title="Pharmacie" >
                                    <span class="sidebar-nav-item-icon icon-li-plus fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Pharmacie</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('dispensation') ?>" title="Dispensation" >
                                    <span class="sidebar-nav-item-icon icon-li-forward fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Dispensation</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('dossiers') ?>" title="Dossiers">
                                    <span class="sidebar-nav-item-icon icon-li-folder-1 fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Dossiers</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('oev') ?>" title="Oev">
                                    <span class="sidebar-nav-item-icon icon-li-loop fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Oev</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('communaute') ?>" title="Communaute">
                                    <span class="sidebar-nav-item-icon icon-li-globe-1 fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Communaute</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('analyse') ?>" title="Rapporting">
                                    <span class="sidebar-nav-item-icon icon-li-bar-chart fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Rapporting </span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('parametres') ?>" title="Parametres">
                                    <span class="sidebar-nav-item-icon icon-li-settings fa-lg"></span>
                                    <span class="sidebar-nav-item aText">Parametres</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </aside>
                <div class="buynow fixed">
                    <a href="http://interlink.mr" target="_new">
                        <img src="<?php echo $this->basePath('themes/datas/images/interlink.png'); ?>" class="img-responsive">
                    </a>
                </div>

            </div>
            <!-- # Sidebar-wrapper -->
            <div id="page-content-wrapper">
                <?php echo $this->inlineScript(); ?>
                <?php echo $this->content; ?>
            </div>
        </div>
        <div class="modal fade" id="infos" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="infosaccueil" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog ">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog ">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="addfact" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="addmed" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="addmot" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="addintol" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <div class="modal fade" id="addmedcourant" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $('#infosaccueil').on('hidden.bs.modal', function () {
                document.getElementById('infosaccueil').innerHTML = '<div class="modal-dialog  modal-md"><div class="modal-content"></div></div>';
                $('#infosaccueil').removeData('bs.modal');
            });
        </script>
        <script type="text/javascript">
            $('#infos').on('hidden.bs.modal', function () {
                document.getElementById('infos').innerHTML = '<div class="modal-dialog  modal-lg"><div class="modal-content"></div></div>';
                $('#infos').removeData('bs.modal');
            });
        </script>
        <script type="text/javascript">
            $('#delete').on('hidden.bs.modal', function () {
                document.getElementById('delete').innerHTML = '<div class="modal-dialog "><div class="modal-content"></div></div>';
                $('#delete').removeData('bs.modal');
            });
        </script>
        <script type="text/javascript">
            $("#addfact").on('hidden.bs.modal', function (event) {
                if ($('.modal:visible').length) //check if any modal is open
                {
                    $('body').addClass('modal-open');//add class to body
                }
                document.getElementById('addfact').innerHTML = '<div class="modal-dialog"><div class="modal-content"></div></div>';
                $('#addfact').removeData('bs.modal');
            });

        </script>
        <script type="text/javascript">
            $("#addmed").on('hidden.bs.modal', function (event) {
                if ($('.modal:visible').length) //check if any modal is open
                {
                    $('body').addClass('modal-open');//add class to body
                }
                document.getElementById('addmed').innerHTML = '<div class="modal-dialog"><div class="modal-content"></div></div>';
                $('#addmed').removeData('bs.modal');
            });
        </script>
        <script type="text/javascript">
            $("#addmot").on('hidden.bs.modal', function (event) {
                if ($('.modal:visible').length) //check if any modal is open
                {
                    $('body').addClass('modal-open');//add class to body
                }
                document.getElementById('addmot').innerHTML = '<div class="modal-dialog"><div class="modal-content"></div></div>';
                $('#addmot').removeData('bs.modal');
            });
        </script>
        <script type="text/javascript">
            $("#addintol").on('hidden.bs.modal', function (event) {
                if ($('.modal:visible').length) //check if any modal is open
                {
                    $('body').addClass('modal-open');//add class to body
                }
                document.getElementById('addintol').innerHTML = '<div class="modal-dialog"><div class="modal-content"></div></div>';
                $('#addintol').removeData('bs.modal');
            });
        </script>
        <script type="text/javascript">
            /* $('#infos').on('hidden.bs.modal', function () {
             document.getElementById('infos').innerHTML = "";
             $('#infos').removeData('bs.modal');
             });*/
            /*$(".modal").on('hidden.bs.modal', function () {
             $(this).data('bs.modal', null);
             });*/
        </script>
    </body>
</html>
