<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'GtnDataTables\Service\DataTableAbstractFactory'        => __DIR__ . '/src/GtnDataTables/Service/DataTableAbstractFactory.php',
  'GtnDataTables\Service\DataTable'                       => __DIR__ . '/src/GtnDataTables/Service/DataTable.php',
  'GtnDataTables\Service\CollectorInterface'              => __DIR__ . '/src/GtnDataTables/Service/CollectorInterface.php',
  'GtnDataTables\Model\Column'                            => __DIR__ . '/src/GtnDataTables/Model/Column.php',
  'GtnDataTables\Model\Result'                            => __DIR__ . '/src/GtnDataTables/Model/Result.php',
  'GtnDataTables\Model\Collection'                        => __DIR__ . '/src/GtnDataTables/Model/Collection.php',
  'GtnDataTables\Exception\UnexpectedValueException'      => __DIR__ . '/src/GtnDataTables/Exception/UnexpectedValueException.php',
  'GtnDataTables\Exception\RuntimeException'              => __DIR__ . '/src/GtnDataTables/Exception/RuntimeException.php',
  'GtnDataTables\Exception\MissingConfigurationException' => __DIR__ . '/src/GtnDataTables/Exception/MissingConfigurationException.php',
  'GtnDataTables\Exception\ExceptionInterface'            => __DIR__ . '/src/GtnDataTables/Exception/ExceptionInterface.php',
  'GtnDataTables\View\AbstractDecorator'                  => __DIR__ . '/src/GtnDataTables/View/AbstractDecorator.php',
  'GtnDataTables\View\Helper\DataTable'                   => __DIR__ . '/src/GtnDataTables/View/Helper/DataTable.php',
  'GtnDataTables\Module'                                  => __DIR__ . '/src/GtnDataTables/Module.php',
);
