<div class="row">
    <div class="col-md-4 col-md-push-4 col-xs-12 sign-box">
        <div class="panel panel-default pale-panel-border-top">
            <div class="panel-heading text-center">
                <h3 class="nm np">
                    <?php echo $this->translate('Changer l\'e-mail'); ?>
                </h3>
            </div>
            <div class="panel-body">
                <br>
                <?php
                $form = $this->changeEmailForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/changeemail'));
                $form->setAttribute('method', 'post');
                ?>
                <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

                <hr>
                <?php if ($status === true) : ?>
                    <div class="alert alert-success"><?php echo $this->translate('Adresse électronique modifiée avec succès.'); ?></div>
                <?php elseif ($status === false) : ?>
                    <div class="alert alert-error"><?php echo $this->translate('Impossible de mettre à jour votre adresse e-mail. Veuillez réessayer.'); ?></div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>






