<div class="row">
    <div class="col-md-4 col-md-push-4 col-xs-12 sign-box">
        <div class="panel panel-default pale-panel-border-top">
            <div class="panel-heading text-center">
                <h3 class="nm np">
                    <?php echo $this->translate('Changer le mot de passe'); ?>
                </h3>
            </div>
            <div class="panel-body">
                <br>
                <?php
                $form = $this->changePasswordForm;

                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/changepassword'));
                $form->setAttribute('method', 'post');
                $form->setAttribute('autocomplete', 'off');

                $emailElement = $form->get('identity');
                $emailElement->setValue($this->zfcUserIdentity()->getEmail());
                ?>

                <?php echo $this->partial('_form.phtml', ['form' => $form]); ?>

                <hr>
                <?php if ($status === true) : ?>
                    <div class="alert alert-success"><?php echo $this->translate('Le mot de passe a été changé avec succès.'); ?></div>
                <?php elseif ($status === false) : ?>
                    <div class="alert alert-error"><?php echo $this->translate('Impossible de mettre à jour votre mot de passe. Veuillez réessayer.'); ?></div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</div>
