<?php
$title = 'Suppression de dossier';
$this->headTitle($title);
$url = $this->url('dossiers', array(
    'action' => 'delete',
    'Nume' => $this->Nume,
        ));
?>
<div class="modal-header">
    <h3 class="panel-title">
        <?php echo $this->escapeHtml($title); ?>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </h3>
</div>
<div class="modal-body">
    <p><h4>Voulez-vous vraiment supprimer le dossier ?</h4></p>
</div>
<div class="modal-footer">
    <form action="<?php echo $url; ?>" method="post">
        <input type="hidden" name="Nume" value="<?php echo  $this->Nume; ?>" />
        <button type="submit" name="del" value="Oui" class="btn btn-danger btn-outline btn-rounded" >Oui</button>
        <span>
        <button type="submit" name="del" value="Non" class="btn btn-default btn-outline btn-rounded" data-dismiss="modal" aria-label="Close">Non</button>
        </span>   
    </form>        
</div>


