<?php 
$title = 'Dossiers';
$this->headTitle($title);
$this->headLink()
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'))
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/extensions/Buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('jszip.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->prependFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'));

?>
<style>
    div.dataTables_length{
position:relative;
float:left;
}
.space{
    margin-right:10px;
}
</style>
<?php
echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
                <?php if ($this->IsAllowed()->isAllowed('Dossiers\Controller\Dossiers', 'add') &&($prefixe===$prefixeagent)) { ?>
				<div class="btn-group pull-right">
                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('dossiers', array('action' => 'add')); ?>">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Créer un nouveau dossier
                    </a>&nbsp;
                </div>
                <?php } ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <?php echo $this->dataTable('dossiersdatatable')->renderHtml(); ?>
                    <!-- /.table-responsive -->
                </div>
            </div>
            <!-- /.panel-body -->
            <div class="panel-footer">
                <div class="row">
                    <div class='col-sm-6'>

                    </div>
                    <?php if ($this->IsAllowed()->isAllowed('Dossiers\Controller\Dossiers', 'add')  &&($prefixe===$prefixeagent)) { ?>
                    <div class="col-sm-2 col-sm-offset-4">
                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('dossiers', array('action' => 'add')); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Créer un nouveau dossier
                        </a>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.panel -->
<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function () {
        $('#dossiersdb').DataTable({
            "processing": true,
            "serverSide": true,
            "ajax": {
                dataType: 'json',
                url: '<?php echo $this->url('dossiers', array('action' => 'data')); ?>',
            },
            deferRender: true,
            dom: 'Blfrtip',
           
            "order": [[ 0, "asc" ]],
            "buttons": [
                {
                    extend: 'copyHtml5',
                    text: 'Copier',
                    className: 'space btn btn-info btn-outline btn-rounded',
                    key: {
                        key: 'c',
                        altKey: true
                    }
                },
                {
                    extend: 'excel',
                    text: '<span class="glyphicon glyphicon-export"></span>Excel',
                    className: 'space btn btn-success btn-outline btn-rounded',
                    key: {
                        key: 'x',
                        altKey: true
                    }
                },
                {
                    extend: 'print',
                    text: '<span class="glyphicon glyphicon-print"></span>Imprimer',
                    message: 'Amnir Echiva',
                    className: 'space btn btn-danger btn-outline btn-rounded',
                    key: {
                        key: 'p',
                        altKey: true
                    }
                },
            ],
            //"lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "Tous"]],
            "responsive": true,
            language: {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ dossiers",
                "infoEmpty": "Affichage 0 à 0 de 0 dossiers",
                "infoFiltered": "(Filtré de _MAX_ dossiers totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Dossiers",
                "loadingRecords": "Chargement...",
                "processing": "<div id='loader'></div>",
                "search": "<b>Rechercher :</b>",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
    });
</script>