
<?php
$title = 'Tableau de bord';
$this->headTitle($title);

$this->headLink()
        ->appendStylesheet($this->basePath('themes/datas/assets/simple-wysiwyg-editor/css/style.css'))
        ->appendStylesheet($this->basePath('themes/datas/bootstrap/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('themes/datas/assets/lineicons-gh-pages/styles.css'))
        ->appendStylesheet($this->basePath('themes/datas/assets/animate.css-master/animate.min.css'))
        ->appendStylesheet($this->basePath('themes/datas/assets/chartist-js-develop/dist/chartist.min.css'))
        ->appendStylesheet($this->basePath('themes/datas/assets/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css'))
        ->appendStylesheet($this->basePath('themes/datas/assets/morris.js-master/morris.css'))
        ->appendStylesheet($this->basePath('themes/datas/css/dashboard-3.css'));
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->appendFile($this->basePath('themes/datas/js/jquery-ui.js'))
        ->appendFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts.js'))
        ->appendFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-more.js'))
        ->appendFile($this->basePath('themes/datas/js/highcharts-data.js'))
        ->appendFile($this->basePath('themes/datas/assets/Highcharts-4.2.5/js/highcharts-3d.js'))
        ->appendFile($this->basePath('themes/datas/assets/chartist-js-develop/dist/chartist.js'))
        ->appendFile($this->basePath('themes/datas/js/raphael-min.js'))
        ->appendFile($this->basePath('themes/datas/assets/morris.js-master/morris.min.js'))
        ->appendFile($this->basePath('themes/datas/js/project-dashboard.js'))
        ->appendFile($this->basePath('themes/datas/js/dashboard-3.js'))
        ->appendFile($this->basePath('themes/datas/js/jquery.sparkline.min.js'));
?>
<div class="row cards">
    <?php if ($this->IsAllowed()->isAllowed('Accueil\Controller\Accueil', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInLeftBig">
            <div class="card info-bg">
                <div class="card-icon info-bg">
                    <i class="fa fa-home" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Accueil</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $accueil['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $accueil['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Depistage\Controller\Depistage', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInDownBig">
            <div class="card danger-bg">
                <div class="card-icon danger-bg">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Depistage</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $depistage['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $depistage['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Laboratoire\Controller\Laboratoire', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInDownBig">
            <div class="card primary-bg">
                <div class="card-icon primary-bg">
                    <i class="flaticon-microscope" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Laboratoire</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $laboratoire['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $laboratoire['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Dispensation\Controller\Dispensation', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInRightBig">
            <div class="card danger-bg">
                <div class="card-icon danger-bg">
                    <i class="fa fa-medkit" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Dispensation</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $dispensation['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $dispensation['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Pharmacie\Controller\Pharmacie', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInLeftBig">
            <div class="card primary-bg">
                <div class="card-icon primary-bg">
                    <i class="flaticon-medicine-2" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Pharmacie</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $pharmacie['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $pharmacie['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Dossiers\Controller\Dossiers', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInDownBig">
            <div class="card success-bg">
                <div class="card-icon success-bg">
                    <i class="fa fa-folder-open" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Dossiers</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $dossiers['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $dossiers['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Oev\Controller\Oev', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInDownBig">
            <div class="card info-bg">
                <div class="card-icon info-bg">
                    <i class="fa fa-child" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Oev</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $oev['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $oev['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->IsAllowed()->isAllowed('Communaute\Controller\Communaute', 'index')) { ?>
        <div class="col-sm-6 col-md-4 col-lg-3 col-xs-12 animated fadeInRightBig">
            <div class="card success-bg">
                <div class="card-icon success-bg">
                    <i class="fa fa-globe" aria-hidden="true"></i>
                </div>
                <div class="display-block card-content">
                    <div>
                        <h4 class="text-center">Communaute</h4>
                    </div>
                    <div class="value">
                        <h4 class="odometer text-center" data-precision="0"><?php echo $communaute['curr']; ?></h4>
                    </div>
                    <hr>
                    <h5  class="lastmonth text-center"><?php echo $lastdate; ?> : <?php echo $communaute['last']; ?></h5>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<!-- debut req 1 -->
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="serologie" data-highcharts-chart="1">
                    <div class="highcharts-container" id="highcharts-2">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Répartition des résultats de dépistage de <?php echo date("M-Y"); ?>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="usetable">
                        <thead>
                            <tr>
                                <th>Dépistage</th>
                                <th>Homme</th>
                                <th>Femme</th>
                                <th>Total</th>
                                <th>Poucentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($tabdepis as $tabdepi) {
                                $a = "default";
                                switch ($tabdepi['titre']) {
                                    case "Négatifs":
                                        $a = "danger";
                                        break;
                                    case "Indéterminés":
                                        $a = "info";
                                        break;
                                    case "Positifs":
                                        $a = "success";
                                        break;
                                }
                                ?>
                                <tr>
                                    <td><span class="label label-<?php echo $a; ?>"><?php echo $this->escapeHtml($tabdepi['titre']); ?></span></td>
                                    <td><?php echo $this->escapeHtml($tabdepi[1]); ?></td>
                                    <td><?php echo $this->escapeHtml($tabdepi[2]); ?></td>
                                    <td><?php echo $this->escapeHtml($tabdepi[3]); ?></td>
                                    <td><?php echo $this->escapeHtml($tabdepi[4]); ?></td>
                                </tr> 
                            <?php } ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- fibr eq 1 -->

<script>
    var tabdepis = <?php echo json_encode($tabdepis); ?>;
    function extract(tabdepis, chaine, pourcent) {
        var str = chaine.split("#");
        var result = Array();
        for (var indice in tabdepis)
        {
            var test = str.indexOf(tabdepis[indice]['titre']);
            if (test != "-1")
                result[tabdepis[indice]['titre']] = tabdepis[indice][pourcent];

        }
        return result;
    }

    $(function () {
        var chaine = "Positifs#Négatifs#Indéterminés";
        var pourcent = 4;
        var result = extract(tabdepis, chaine, pourcent);
        // Create the chart
        $('.serologie').highcharts({
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Répartition des résultats de dépistage <?php echo date("M-Y"); ?>'
            },
            credits: {
                enabled: false
            },
            subtitle: {
                //text: 'Click the slices to view versions. Source: netmarketshare.com.'
            },
            plotOptions: {
                series: {
                    dataLabels: {
                        enabled: true,
                        format: '{point.name}: {point.y:.1f}%'
                    }
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
            },
            series: [{
                    name: 'Sérologie',
                    colorByPoint: true,
                    data: [{
                            name: 'Positifs',
                            y: parseInt(result['Positifs']),
                            drilldown: 'Positifs'
                        }, {
                            name: 'Négatifs',
                            y: parseInt(result['Négatifs']),
                            drilldown: 'Négatifs'
                        }, {
                            name: 'Indéterminés',
                            y: parseInt(result['Indéterminés']),
                            drilldown: 'Indéterminés'
                        }
                    ]
                }],
            /*drilldown: {
             series: [{
             name: 'iExplorer',
             id: 'iExplorer',
             data: [
             ['v11.0', 24.13],
             ['v8.0', 17.2],
             ['v9.0', 8.11],
             ['v10.0', 5.33],
             ['v6.0', 1.06],
             ['v7.0', 0.5]
             ]
             }, {
             name: 'Chrome',
             id: 'Chrome',
             data: [
             ['v40.0', 5],
             ['v41.0', 4.32],
             ['v42.0', 3.68],
             ['v39.0', 2.96],
             ['v36.0', 2.53],
             ['v43.0', 1.45],
             ['v31.0', 1.24],
             ['v35.0', 0.85],
             ['v38.0', 0.6],
             ['v32.0', 0.55],
             ['v37.0', 0.38],
             ['v33.0', 0.19],
             ['v34.0', 0.14],
             ['v30.0', 0.14]
             ]
             }, {
             name: 'Firefox',
             id: 'Firefox',
             data: [
             ['v35', 2.76],
             ['v36', 2.32],
             ['v37', 2.31],
             ['v34', 1.27],
             ['v38', 1.02],
             ['v31', 0.33],
             ['v33', 0.22],
             ['v32', 0.15]
             ]
             }, {
             name: 'Safari',
             id: 'Safari',
             data: [
             ['v8.0', 2.56],
             ['v7.1', 0.77],
             ['v5.1', 0.42],
             ['v5.0', 0.3],
             ['v6.1', 0.29],
             ['v7.0', 0.26],
             ['v6.2', 0.17]
             ]
             }, {
             name: 'Opera',
             id: 'Opera',
             data: [
             ['v12.x', 0.34],
             ['v28', 0.24],
             ['v27', 0.17],
             ['v29', 0.16]
             ]
             }]
             }
             */});
    });
</script>