<?php
$this->headLink()
        ->prependStylesheet($this->basePath('bootstrap-select.min.css'));
$this->inlineScript()
        ->appendFile($this->basePath('bootstrap-select.min.js'))
        ->appendFile($this->basePath('defaults-fr_FR.js'));

$title = 'Droits d\'accès';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('parametres', array('action' => 'droits', 'Nume' => $Nume)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<style>
    .bootstrap-select:not([class*=col-]):not([class*=form-control]):not(.input-group-btn) {
        width: 500px;
    }
</style>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading clearfix">
                <h2 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h2>
                <?php
                echo $this->formHidden($form->get('Nume'));
                ?>

            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example2">
                        <tbody>
                            <?php foreach ($all as $resource) { ?>
                                <tr>
                                    <td class="col-md-4"><?php echo $this->escapeHtml($resource['title']); ?></td>
                                    <td class="col-md-8">
                                        <?php
                                        echo $this->formSelect($form->get($resource['id']));
                                        echo $this->formElementErrors($form->get($resource['id']));
                                        ?>
                                    </td>
                                </tr> 
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <div class="panel-footer">
                &nbsp;&nbsp;<button type="reset" name="rest" value="Annuler" class="btn btn-default pull-right" >Annuler</button>&nbsp;&nbsp;
                &nbsp;&nbsp;<button type="submit" name="submit" value="Valider"  class="btn btn-primary pull-right">Valider</button>&nbsp;&nbsp;<br /><br />
                &nbsp;&nbsp;
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag() ?>