<?php
$title = 'Modifier Un Profil';
$this->headTitle($title);

$this->headLink()
        ->prependStylesheet($this->basePath('bootstrap-select.min.css'));
$this->inlineScript()
        ->appendFile($this->basePath('bootstrap-select.min.js'))
        ->appendFile($this->basePath('defaults-fr_FR.js'));


$form = $this->form;
$form->setAttribute('action', $this->url('parametres', array('action' => 'edit', 'Nume' => $this->rid,)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title col-sm-4"><?php echo $this->escapeHtml($title); ?></h4>
        </div>
        <div class="modal-body">
            <?php echo $this->formHidden($form->get('rid')); ?>
            <div class="form-group">
                <label class="control-label col-sm-4">
                    <?php echo $this->formLabel($form->get('role_name')); ?>
                </label>
                <div class="col-sm-8">
                    <?php
                    echo $this->formInput($form->get('role_name'));
                    echo $this->formElementErrors($form->get('role_name'));
                    ?>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-4">
                    <?php echo $this->formLabel($form->get('status')); ?>
                </label>
                <div class="radio col-sm-8">
                    <div class="radio">
                        <label>
                            <input type="radio" class="primary" name="status" value="Active" <?php if ($form->get('status')->getValue() == "Active") echo "checked"; ?> > Actif
                            <span class="cr "><i class="cr-icon glyphicon glyphicon-ok "></i></span>
                        </label>
                        <label>
                            <input type="radio" class="primary" name="status" value="Inactive" <?php if ($form->get('status')->getValue() == "Inactive") echo "checked"; ?> > Inactif
                            <span class="cr "><i class="cr-icon glyphicon glyphicon-ok"></i></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" name="submit" class="btn btn-primary">Valider</button>
            <span>
                <button type="reset" name="rest" value="Annuler" class="btn btn-default">Annuler</button>
            </span>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>