<?php
$title = 'Parametres';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('parametres', array('action' => 'index'/* , 'Nume' => $this->Nume, */)));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
$this->headLink()
        ->prependStylesheet($this->basePath('bootstrap-select.min.css'))
        ->prependStylesheet($this->basePath('themes/datas/css/tables.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/bootstrap-table-develop/src/bootstrap-table.css'))
        ->prependStylesheet($this->basePath('themes/datas/assets/DataTables-1.10.12/media/css/dataTables.bootstrap.css'));
?>

<!-- Page Level JS -->
<?php
$this->inlineScript()
        ->appendFile($this->basePath('themes/datas/assets/bootstrap-table-develop/dist/bootstrap-table.min.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/jquery.dataTables.js'))
        ->appendFile($this->basePath('themes/datas/assets/DataTables-1.10.12/media/js/dataTables.bootstrap.js'))
        ->appendFile($this->basePath('bootstrap-select.min.js'));
?>
<!-- row -->
<?php
echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger'));
echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary-border-top">
            <div class="panel-heading">
                <h4 class="panel-title pull-left" style="padding-top: 7.5px;">
                    <?php echo $this->escapeHtml($title); ?>
                </h4>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#Profils" data-toggle="tab">Profils</a></li>
                    <li><a href="#Utilisateurs" data-toggle="tab">Utilisateurs</a></li>
                    <li><a href="#Centre" data-toggle="tab">Centre</a></li>
                    <li><a href="#accueil" data-toggle="tab">Options de Sélection</a></li>
                    <li><a href="#pharmacie" data-toggle="tab">Pharmacie</a></li>                    
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="Profils">
                        <div class="panel panel-primary-border-top">
                            <div class="panel-heading clearfix">
                                <?php if ($this->IsAllowed()->isAllowed('Parametres\Controller\Parametres', 'add')) { ?>
                                    <div class="btn-group pull-right">
                                        <a title="Ajouter Un Profil" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'add')); ?>">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Un Profil
                                        </a>
                                    </div>
                                <?php } ?>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                                        <thead>
                                            <tr>
                                                <th>Profil</th>
                                                <th>Statut</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($roles as $role) : ?>
                                                <tr>
                                                    <td><?php echo $this->escapeHtml($role->role_name); ?></td>
                                                    <td>
                                                        <?php
                                                        if ($role->status == "Active") {
                                                            echo "Actif";
                                                        } else if ($role->status == "Inactive") {
                                                            echo "Inactif";
                                                        } else {
                                                            echo $this->escapeHtml($role->$role->status);
                                                        }
                                                        ?>
                                                    </td>
                                                    <td>
                                                        <a  title="Modifier Profil <?php echo $this->escapeHtml($role->role_name); ?>" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'edit', 'Nume' => $role->rid)); ?>">
                                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                        </a>
                                                        <a data-toggle="modal" data-target="#infos" title="Supprimer Profil <?php echo $this->escapeHtml($role->role_name); ?>" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'delete', 'Nume' => $role->rid)); ?>">
                                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                        </a>
                                                        <a  title="Gestion Droits d'accès <?php echo $this->escapeHtml($role->role_name); ?>" class="btn btn-sm btn-info btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'droits', 'Nume' => $role->rid)); ?>">
                                                            <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                                                        </a>
                                                    </td>
                                                </tr> 
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.table-responsive -->
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <?php if ($this->IsAllowed()->isAllowed('Parametres\Controller\Parametres', 'add')) { ?>
                                            <div class="btn-group pull-right">
                                                <a title="Ajouter Un Profil" class="btn btn-primary btn-outline btn-rounded pull-right" href="<?php echo $this->url('parametres', array('action' => 'add')); ?>">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Un Profil
                                                </a>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="Utilisateurs">
                        <div class="panel panel-success-border-top">
                            <div class="panel-heading clearfix">
                                <div class="btn-group pull-right">
                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->escapeUrl($this->redirect) : '') ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <?php echo $this->translate('Ajouter Un Utilisateur'); ?>
                                    </a>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example2">
                                        <thead>
                                            <tr>
                                                <th>Identifiant</th>
                                                <th>Nom & Prénom</th>
                                                <th>E-mail</th>
                                                <th>Statut</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($users as $user) : ?>
                                                <tr>
                                                    <td><?php echo $this->escapeHtml($user->username); ?></td>
                                                    <td><?php echo $this->escapeHtml($user->display_name); ?></td>
                                                    <td><?php echo $this->escapeHtml($user->email); ?></td>
                                                    <td><?php
                                                        if ($user->state == 1)
                                                            echo $this->escapeHtml("Actif");
                                                        else
                                                            echo $this->escapeHtml("Inactif");
                                                        ?></td>
                                                    <td>
                                                        <?php if ($user->state == 1) { ?>
                                                            <a title="Suspendre" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'statue', 'Nume' => $user->user_id)); ?>">
                                                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                            </a>
                                                        <?php } else { ?>
                                                            <a title="active" class="btn btn-sm btn-info btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'statue', 'Nume' => $user->user_id)); ?>">
                                                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                                            </a>
                                                        <?php } ?>
                                                        <a  title="Modifier" class="btn btn-sm btn-success btn-outline btn-rounded" data-toggle="modal" href="<?php echo $this->url('parametres', array('action' => 'edituser', 'Nume' => $user->user_id)); ?>">
                                                            <span class="fa fa-edit" aria-hidden="true"></span>
                                                        </a>
                                                        <a  title="Profil" class="btn btn-sm btn-info btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'role', 'Nume' => $user->user_id)); ?>">
                                                            <span class="glyphicon glyphicon-sort" aria-hidden="true"></span>
                                                        </a>
                                                        <a  title="Re-initialisation mot de passe" class="reinitpwbtn btn btn-sm btn-primary btn-outline btn-rounded" data-toggle="modal" href="#reinitpwmodal" id="<?php echo $user->user_id ?>">
                                                            <span class="fa fa-key" aria-hidden="true"></span>
                                                        </a>
                                                    </td>
                                                </tr> 
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.table-responsive -->                        
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="btn-group pull-right">
                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->escapeUrl($this->redirect) : '') ?>">
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <?php echo $this->translate('Ajouter Un Utilisateur'); ?>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="Centre">
                        <div class="panel panel-success-border-top">
                            <div class="panel-heading clearfix">
                                <?php if ($this->IsAllowed()->isAllowed('Parametres\Controller\Parametres', 'addcentre')) { ?>
                                <div class="btn-group pull-right">
                                        <a title="Ajouter Un Centre" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addcentre')); ?>">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Un Centre
                                        </a>
                                    </div>
                                <?php } ?>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example2">
                                        <thead>
                                            <tr>
                                                <th>Code Region</th>
                                                <th>Region</th>
                                                <th>Code Structure</th>
                                                <th>Structure</th>
                                                <th>Prefixe</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($Centre as $centre) : ?>
                                                <tr>
                                                    <td><?php echo $this->escapeHtml($centre->Code_region); ?></td>
                                                    <td><?php echo $this->escapeHtml($centre->Region); ?></td>
                                                    <td><?php echo $this->escapeHtml($centre->Code_struct); ?></td>
                                                    <td><?php echo $this->escapeHtml($centre->Structure); ?></td>
                                                    <td><?php echo $this->escapeHtml($centre->Prefixe); ?></td>
                                                    <td>
                                                        <a  title="Modifier Centre <?php echo $this->escapeHtml($centre->Id); ?>" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'editcentre', 'Nume' => $centre->Id)); ?>">
                                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                        </a>
                                                        <a data-toggle="modal" data-target="#infos" title="Supprimer Centre <?php echo $this->escapeHtml($centre->Id); ?>" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deletecentre', 'Nume' => $centre->Id)); ?>">
                                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                        </a>
                                                    </td>
                                                </tr> 
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                                <!-- /.table-responsive -->                        
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <?php if ($this->IsAllowed()->isAllowed('Parametres\Controller\Parametres', 'addcentre')) { ?>
                                <div class="btn-group pull-right">
                                        <a title="Ajouter Un Centre" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addcentre')); ?>">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Un Centre
                                        </a>
                                    </div>
                                <?php } ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="accueil">
                        <div class="panel panel-warning-border-top">
                            <div class="panel-heading clearfix">
                                <div class="btn-group pull-right">
                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addliste')); ?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Option
                                    </a>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">

                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example3">
                                        <thead>
                                            <tr>
                                                <th>Désignation</th>
                                                <th>Type</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($lists as $list) : ?>
                                                <tr>
                                                    <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                    <td><?php echo $this->escapeHtml($list->Typ_); ?></td>
                                                    <td>
                                                        <a  title="Modifier" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'editliste', 'Nume' => $list->Nume)); ?>">
                                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                        </a>
                                                        <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deleteliste', 'Nume' => $list->Nume)); ?>">
                                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                        </a>

                                                    </td>
                                                </tr> 
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="panel-footer">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="btn-group pull-right">
                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addliste')); ?>">
                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Option
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="pharmacie">
                        <br />						
                        <div class="row">
                            <div class="col-sm-12">
                                <ul class="nav nav-tabs">
                                    <li class="active"><a href="#dci" data-toggle="tab">Désignation</a></li>
                                    <li><a href="#Dosage" data-toggle="tab">Dosage</a></li>
                                    <li><a href="#Forme" data-toggle="tab">Forme</a></li>
                                    <li><a href="#Provenance" data-toggle="tab">Provenance</a></li>
                                    <li><a href="#Fabricant" data-toggle="tab">Fabricant</a></li>
                                    <li><a href="#Priseencharge" data-toggle="tab">Prise en charge</a></li>
                                    <li><a href="#Destination" data-toggle="tab">Destination</a></li>
                                    <li><a href="#posodefaut" data-toggle="tab">Forme et posologie par défaut</a></li>
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane fade in active" id="dci">
                                        <div class="panel panel-warning-border-top">
                                            <div class="panel-heading clearfix">
                                                <div class="btn-group pull-right">
                                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'adddci')); ?>">
                                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Désignation
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="panel-body">
                                                <div class="table-responsive">
                                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example4">
                                                        <thead>
                                                            <tr>
                                                                <th>Désignation</th>
                                                                <th>Type</th>
                                                                <th>Action</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php foreach ($dcis as $list) : ?>
                                                                <tr>
                                                                    <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                    <td><?php
                                                                        if ($list->Typ_ == 1)
                                                                            echo "Medicaments";
                                                                        if ($list->Typ_ == 3)
                                                                            echo "Arv";
                                                                        if ($list->Typ_ == 2)
                                                                            echo "Consommables";
                                                                        if ($list->Typ_ == 4)
                                                                            echo "Laboratoire";
                                                                        ?></td>
                                                                    <td>
                                                                        <a  title="Modifier" class="btn btn-sm btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'editdci', 'Nume' => $list->Nume)); ?>">
                                                                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                                                        </a>
                                                                        <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deletedci', 'Nume' => $list->Nume)); ?>">
                                                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                        </a>

                                                                    </td>
                                                                </tr> 
                                                            <?php endforeach; ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <div class="panel-footer">
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <div class="btn-group pull-right">
                                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'adddci')); ?>">
                                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Option
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="Dosage">
                                        <div class="panel panel-warning-border-top">
                                            <div class="panel-heading clearfix">
                                                <div class="btn-group pull-right">
                                                    <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'adddosa')); ?>">
                                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Dosage
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="panel-body">
                                                <div class="table-responsive">
                                                    <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example5">
                                                        <thead>
                                                            <tr>
                                                                <th>Désignation</th>
                                                                <th>Action</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php foreach ($Dosage as $list) : ?>
                                                                <tr>
                                                                    <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                    <td>
                                                                        <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deletedosa', 'Nume' => $list->Nume)); ?>">
                                                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                        </a>

                                                                    </td>
                                                                </tr> 
                                                            <?php endforeach; ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                            <div class="panel-footer">
                                                <div class="row">
                                                    <div class="col-sm-12">
                                                        <div class="btn-group pull-right">
                                                            <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'adddosa')); ?>">
                                                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Dosage
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="Forme">
                                        <div class="panel-heading clearfix">
                                            <div class="btn-group pull-right">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addgale')); ?>">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Forme
                                                </a>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example6">
                                                    <thead>
                                                        <tr>
                                                            <th>Désignation</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach ($Forme as $list) : ?>
                                                            <tr>
                                                                <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                <td>
                                                                    <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deletegale', 'Nume' => $list->Nume)); ?>">
                                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                    </a>

                                                                </td>
                                                            </tr> 
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="btn-group pull-right">
                                                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addgale')); ?>">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Forme
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="tab-pane" id="Provenance">
                                        <div class="panel-heading clearfix">
                                            <div class="btn-group pull-right">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addprov')); ?>">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Provenance
                                                </a>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example7">
                                                    <thead>
                                                        <tr>
                                                            <th>Désignation</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach ($Provenance as $list) : ?>
                                                            <tr>
                                                                <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                <td>
                                                                    <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deleteprov', 'Nume' => $list->Nume)); ?>">
                                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                    </a>

                                                                </td>
                                                            </tr> 
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="btn-group pull-right">
                                                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addprov')); ?>">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Provenance
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="tab-pane" id="Fabricant">
                                        <div class="panel-heading clearfix">
                                            <div class="btn-group pull-right">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addfabr')); ?>">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Fabricant
                                                </a>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example8">
                                                    <thead>
                                                        <tr>
                                                            <th>Désignation</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach ($Fabricant as $list) : ?>
                                                            <tr>
                                                                <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                <td>
                                                                    <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deletefabr', 'Nume' => $list->Nume)); ?>">
                                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                    </a>

                                                                </td>
                                                            </tr> 
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="btn-group pull-right">
                                                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addfabr')); ?>">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Fabricant
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="tab-pane" id="Priseencharge">
                                        <div class="panel-heading clearfix">
                                            <div class="btn-group pull-right">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addchrg')); ?>">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Prise en charge
                                                </a>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example9">
                                                    <thead>
                                                        <tr>
                                                            <th>Désignation</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach ($Priseencharge as $list) : ?>
                                                            <tr>
                                                                <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                <td>
                                                                    <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deletechrg', 'Nume' => $list->Nume)); ?>">
                                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                    </a>

                                                                </td>
                                                            </tr> 
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="btn-group pull-right">
                                                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'addchrg')); ?>">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Prise en charge
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="tab-pane" id="Destination">
                                        <div class="panel-heading clearfix">
                                            <div class="btn-group pull-right">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'additemdest')); ?>">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Destination
                                                </a>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example10">
                                                    <thead>
                                                        <tr>
                                                            <th>Désignation</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach ($Destination as $list) : ?>
                                                            <tr>
                                                                <td><?php echo $this->escapeHtml($list->Desi); ?></td>
                                                                <td>
                                                                    <a data-toggle="modal" data-target="#infos" title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'deleteitemdest', 'Nume' => $list->Nume)); ?>">
                                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                    </a>

                                                                </td>
                                                            </tr> 
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="btn-group pull-right">
                                                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'additemdest')); ?>">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Destination
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="posodefaut">
                                        <div class="panel-heading clearfix">
                                            <div class="btn-group pull-right">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" data-toggle="modal" href="#posologiearvform">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Posologie ARV
                                                </a>
                                            </div>
                                            <div class="btn-group pull-left">
                                                <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" data-toggle="modal"  href="#posologiemedform">
                                                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Posologie Médicament courant
                                                </a>
                                            </div>
                                        </div>
                                        <div class="panel-body">
                                            <div class="table-responsive">
                                                <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="posodataTables">
                                                    <thead>
                                                        <tr>
                                                            <th>Désignation</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <?php foreach ($posologie as $k => $poso) : $poso = str_replace(";", " ", $poso); ?>
                                                            <tr>
                                                                <td><?php echo $this->escapeHtml($poso); ?></td>
                                                                <td>
                                                                    <a title="Supprimer" class="btn btn-sm btn-danger btn-outline btn-rounded" data-toggle="modal" id="<?php echo $k; ?>" href="#deletemodalform">
                                                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                                                    </a>
                                                                </td>
                                                            </tr> 
                                                        <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>

                                        <div class="panel-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="btn-group pull-right">
                                                        <a title="Nouveau" class="btn btn-primary btn-outline btn-rounded" href="<?php echo $this->url('parametres', array('action' => 'additemdest')); ?>">
                                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Ajouter Destination
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>	
                    </div>
                    <!-- /.table-responsive -->
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->openTag($form); ?> 
<div class="modal fade" id="posologiemedform" tabindex="-1" role="dialog" aria-labelledby="posologiemedform" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <?php echo $this->formHidden($form->get('PosoDefa')); ?> 
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Medicament courant - Forme et posologie par défaut</h4>
            </div>
            <div class="modal-body">
                <div class="form-group ">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('MedDci_')); ?>
                    </label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formSelect($form->get('MedDci_'));
                        echo $this->formElementErrors($form->get('MedDci_'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('MedForm')); ?>
                    </label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formSelect($form->get('MedForm'));
                        echo $this->formElementErrors($form->get('MedForm'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('MedNomb')); ?>
                    </label>
                    <div class="col-md-4">
                        <?php
                        echo $this->formInput($form->get('MedNomb'));
                        echo $this->formElementErrors($form->get('MedNomb'))
                        ?>
                    </div>
                    <div class="col-sm-5">
                        <?php
                        echo $this->formSelect($form->get('MedUnit'));
                        echo $this->formElementErrors($form->get('MedUnit'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('MedFois')); ?>
                    </label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formSelect($form->get('MedFois'));
                        echo $this->formElementErrors($form->get('MedFois'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('MedDure')); ?>
                    </label>
                    <div class="col-md-4">
                        <?php
                        echo $this->formInput($form->get('MedDure'));
                        echo $this->formElementErrors($form->get('MedDure'))
                        ?>
                    </div>
                    <div class="col-md-5">
                        <?php
                        echo $this->formSelect($form->get('MedDureTyp_'));
                        echo $this->formElementErrors($form->get('MedDureTyp_'))
                        ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" name="ajtdefautmed" id="Med" class="btn btn-primary ajtdefaut">Valider</button>
                <span>
                    <button type="button" name="rest" value="Annuler" class="btn btn-default" data-dismiss="modal" aria-label="Close">Annuler</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="posologiearvform" tabindex="-1" role="dialog" aria-labelledby="posologiearvform" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">ARV - Forme et posologie par défaut</h4>
            </div>
            <div class="modal-body">
                <div class="form-group ">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('ArvPrsc')); ?>
                    </label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formSelect($form->get('ArvPrsc'));
                        echo $this->formElementErrors($form->get('ArvPrsc'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('ArvForm')); ?>
                    </label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formSelect($form->get('ArvForm'));
                        echo $this->formElementErrors($form->get('ArvForm'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('ArvNomb')); ?>
                    </label>
                    <div class="col-md-4">
                        <?php
                        echo $this->formInput($form->get('ArvNomb'));
                        echo $this->formElementErrors($form->get('ArvNomb'))
                        ?>
                    </div>
                    <div class="col-sm-5">
                        <?php
                        echo $this->formSelect($form->get('ArvUnit'));
                        echo $this->formElementErrors($form->get('ArvUnit'))
                        ?>
                    </div>
                </div>
                <div class="form-group form-group-md">
                    <label class="control-label col-md-3">
                        <?php echo $this->formLabel($form->get('ArvFois')); ?>
                    </label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formSelect($form->get('ArvFois'));
                        echo $this->formElementErrors($form->get('ArvFois'))
                        ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" name="ajtdefautarv" id="Arv" class="btn btn-primary ajtdefaut">Valider</button>
                <span>
                    <button type="button" name="rest" value="Annuler" class="btn btn-default" data-dismiss="modal" aria-label="Close">Annuler</button>
                </span>
            </div>
        </div>

    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<div class="modal fade " id="reinitpwmodal" tabindex="-1" role="dialog"> <!-- class modal-signin -->
    <div class="modal-dialog" role="document">
        
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <form class="row text-center" id="myForm">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title" id ="username"> Mot de passe </h3><small>Reinitialisation du mot de passe</small>
                    </div>
                    <div class="modal-body panel-body">
                        <br>
                        <div class="col-md-8 col-md-push-2">
                            <div class="text-center">
                                <input type="hidden" class="form-control" id="Numeuser">
                                <input type="password" class="form-control" id="newpw" minlength=6 placeholder="Nouveau mot de passe" required="required">
                                <hr />
                                <input type="submit" style="display:none" value="Subscribe Now!" class="btn btn-success" />
                                <input type="button" id="submitid" value="Valider!" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
                <!-- #Modal -->
            </form>
    </div>
</div>


<form action ="<?php echo $this->url('parametres', array('action' => 'deleteposo')); ?>" method="post">
    <div class="modal fade" id="deletemodalform" tabindex="-1" role="dialog" aria-labelledby="sortiemodalform" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="panel-title">
                        <b>Suppression de posologie</b>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </h3>
                </div>
                <div class="modal-body">
                    <p><h4>Voulez-vous vraiment supprimer la posologie?</h4></p>
                </div>
                <div class="modal-footer">
                    <input name="PosoDefa" type="hidden" id="Posodefasup" value="">
                    <button type="submit" name="del" id="suppaction" value="Oui" class="btn btn-danger btn-outline btn-rounded" >Oui</button>
                    <span>
                        <button type="button" name="del" value="Non" class="btn btn-default btn-outline btn-rounded" data-dismiss="modal" aria-label="Close">Non</button>
                    </span>           
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        var forme = <?php echo json_encode($tabforme); ?>;
        var formemedi = <?php echo json_encode($tabformemedi); ?>;
        var posologie = <?php echo json_encode($posologie); ?>;
        var strposologie = posologie.join("#");
        $('#PosoDefa').val(strposologie);
        $('#dataTables-example').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Profls",
                "infoEmpty": "Affichage 0 à 0 de 0 Profls",
                "infoFiltered": "(Filtré de _MAX_ Profls totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Profls",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        var usertable = $('#dataTables-example2').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Utilisateurs",
                "infoEmpty": "Affichage 0 à 0 de 0 Utilisateurs",
                "infoFiltered": "(Filtré de _MAX_ Utilisateurs totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Utilisateurs",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example3').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example4').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example5').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example6').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example7').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example8').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example9').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('#dataTables-example10').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        var posotable = $('#posodataTables').DataTable({
            responsive: true,
            "language": {
                "decimal": "",
                "emptyTable": "aucune donnée disponible",
                "info": "Affichage de _START_ à _END_ de _TOTAL_ Options",
                "infoEmpty": "Affichage 0 à 0 de 0 Options",
                "infoFiltered": "(Filtré de _MAX_ Options totales)",
                "infoPostFix": "",
                "thousands": ",",
                "lengthMenu": "Afficher _MENU_ Options",
                "loadingRecords": "Chargement...",
                "processing": "En traitement...",
                "search": "Recherche :",
                "zeroRecords": "Aucun enregistrements correspondants trouvés",
                "paginate": {
                    "first": "Premier",
                    "last": "Dernier",
                    "next": "Suivant",
                    "previous": "Précédent"
                },
                "aria": {
                    "sortAscending": ": Activer pour trier la colonne en ordre croissant",
                    "sortDescending": ": Activer pour trier la colonne en descendant"
                }
            }
        });
        $('.MedSui.form-control.ArvPrsc').on('change', function () {
            setformArv($('#ArvForm'), $('#ArvPrsc').val());
        });
        $('.MedSui.form-control.MedDci').on('change', function () {
            setformMedi($('#MedForm'), $('#MedDci_').val());
        });
        $('.btn.btn-primary.ajtdefaut').on('click', function () {
            var id = this.id;
            setposostr(id);
        });

        $('#posodataTables').on('click', 'tbody tr a', function () {
            id = this.id;
        });
        $('#suppaction').on('click', function () {
            delposo(id);
        });
        function setposostr(id) {
            var stradd = "";
            if (id == 'Med')
                var dci = $('#MedDci_ option[value=' + $('#MedDci_').val() + ']').text();
            else
                var dci = $('#ArvPrsc').val();

            if (dci) {
                if (!checkdefaut(dci)) {
                    stradd += '#' + dci + ";" + $('#' + id + 'Form').val() + ";";
                    stradd += $('#' + id + 'Nomb').val() + ";";
                    stradd += $('#' + id + 'Unit').val() + ";";
                    stradd += $('#' + id + 'Fois').val() + ";";
                    if (id == 'Med')
                    {
                        stradd += $('#' + id + 'Dure').val() + ";";
                        stradd += $('#' + id + 'DureTyp_').val() + ";";
                    }
                    else
                        stradd += ";;";
                }
                else
                    alert('existe deja');
            }
            $('#PosoDefa').val(strposologie + stradd);
            document.getElementById("posologie").submit();
        }
        function delposo(id) {
            if (id)
                posologie.splice(id, 1);
            strposologie = posologie.join("#");
            $('#Posodefasup').val(strposologie);
        }

        function checkdefaut(dci) {
            var trouv = false;
            for (var i = 0; i < posologie.length; i++) {
                var tabposologie = posologie[i].split(';');
                if (tabposologie.indexOf(dci) == -1 && tabposologie.indexOf('\n' + dci) == -1)
                {
                    trouv = false;
                }
                else {
                    trouv = true;
                    break;
                }
            }

            return (trouv);
        }
        function setformArv(AvrForm, numedci) {
            AvrForm.empty();
            AvrForm.append($('<option>', {
                value: "",
                text: ""
            }));
            for (var i = 0; i < forme.length; i++)
            {
                if (forme[i]['Dci'] === numedci)
                {
                    AvrForm.append($('<option>', {
                        value: forme[i]['Desi'],
                        text: forme[i]['Desi']
                    }));

                }
            }
            AvrForm.selectpicker('refresh');
        }
        function setformMedi(MediForm, numedci) {
            MediForm.empty();
            MediForm.append($('<option>', {
                value: "",
                text: ""
            }));
            for (var i = 0; i < formemedi.length; i++)
            {
                if (formemedi[i]['Dci'] === numedci)
                {
                    MediForm.append($('<option>', {
                        value: formemedi[i]['Desi'],
                        text: formemedi[i]['Desi']
                    }));
                }
            }
            MediForm.selectpicker('refresh');
        }
        
   $('#dataTables-example2 tbody').on('click', '.reinitpwbtn', function () {
       var tr = this.closest('tr');
       var donnee = usertable.row(tr).data();
       document.getElementById('username').innerHTML =donnee[1];
       var id=this.id;
       $('#Numeuser').val(id);
   });      
        
 $('#submitid').on('click', function () {
     var $myForm = $('#myForm');
          if(! $myForm[0].checkValidity()) {
            $myForm.find(':submit').click();
           }  
           else
           { 
               var Numeuser= $('#Numeuser').val();
               var password= $('#newpw').val();
              $.ajax({
                type: 'POST',
                url: '<?php echo $this->url('parametres', array('action' => 'resetpassword')); ?>',
                dataType: 'json',
                data: {'user_id': Numeuser,'password':password},
                success: function (data) {
                    $('#Numeuser').val("");
                    $('#newpw').val("");
                    $('#reinitpwmodal').modal('hide');
                    
               /* if(data.Nume>0)
                {
                    var t = Array();
                    t['1']='Masculin';
                    t['2']='Feminin';
                    var sexe = '';
                    if(data.Sexe){
                        sexe = t[data.Sexe];
                    } 
                }
                if(data.Nume===-1)
                {
                    alert("Le patient a déjà participé à une activité semblable le "+data.Modi);
                }
                */},
                error: function (data) {
                    alert('Dossier non trouvé.');
                    console.log(data);
                }
            }); 
           }
        });

    });
</script>