<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title col-sm-4">Parametres</h4>
        </div>
        <div class="modal-body">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li class="active"><a href="#Profils" data-toggle="tab">Profils</a></li>
                <li><a href="#Utilisateurs" data-toggle="tab">Utilisateurs</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane fade in active" id="Profils">
                    <br />
                    <div class="table-responsive">
                        <table width="100%" class="table table-striped table-bordered"  cellspacing="0" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>Nom de Profil</th>
                                    <th>Statue de Profil</th>
                                    <th>Detail</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($roles as $entr) : ?>
                                    <tr>
                                        <td><?php echo $this->escapeHtml($entr->role_name); ?></td>
                                        <td><?php echo $this->escapeHtml($entr->status); ?></td>
                                        <td>
                                        </td>
                                    </tr> 
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <div class="tab-pane fade" id="Utilisateurs">
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" name="submit" class="btn btn-primary">Valider</button>
            <span>
                <button type="reset" name="rest" value="Annuler" class="btn btn-default" >Annuler</button>
            </span>
        </div>
    </div>
</div>